Repository artsy/emission, pull requests merged in 2018-05, with the labels that each got.

#1052 [Home] Add support for changing tabs from native code (for 1.4.x)
  CHANGELOG.md
  Pod/Classes/ViewControllers/ARComponentViewController.h
  Pod/Classes/ViewControllers/ARComponentViewController.m
  Pod/Classes/ViewControllers/ARHomeComponentViewController.h
  Pod/Classes/ViewControllers/ARHomeComponentViewController.m
  src/lib/Scenes/Home/index.tsx
Labels: Home

#1056 [Analytics] Update home analytics for tab changes and inital tab props
  CHANGELOG.md
  src/lib/Scenes/Home/__stories__/Home.story.tsx
  src/lib/Scenes/Home/__tests__/index-tests.tsx
  src/lib/Scenes/Home/index.tsx
Labels: Analytics, Home

#1067 remove dangerfile.ts from TS include
  tsconfig.json
Labels: Merge On Green

#1074 [Bidding flow] Add the ability for first-time bidders to add billing address
  CHANGELOG.md
  src/lib/Components/Bidding/Screens/BillingAddress.tsx
  src/lib/Components/Bidding/Screens/ConfirmBid.tsx
  src/lib/Components/Bidding/Screens/ConfirmFirstTimeBid.tsx
  src/lib/Components/Bidding/Screens/__tests__/BillingAddress-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/ConfirmFirstTimeBid-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/__snapshots__/BillingAddress-tests.tsx.snap
  src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmBid-tests.tsx.snap
  src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmFirstTimeBid-tests.tsx.snap
  src/lib/Components/Bidding/Validators/__tests__/index-tests.ts
  src/lib/Components/Bidding/Validators/index.ts
  src/lib/Components/Bidding/__stories__/BidFlow.story.tsx
Labels: Merge On Green

#1079 [Analytics] For the new bidflow
  CHANGELOG.md
  src/lib/Components/Bidding/Screens/BillingAddress.tsx
  src/lib/Components/Bidding/Screens/ConfirmBid.tsx
  src/lib/Components/Bidding/Screens/ConfirmFirstTimeBid.tsx
  src/lib/Components/Bidding/Screens/SelectMaxBid.tsx
  src/lib/utils/track.ts
Labels: Analytics
