Repository artsy/emission, pull requests merged in 2019-08, with the labels that each got.

#1764 [Artist/Card] Fix shadow and performance warning.
  CHANGELOG.md
  Example/Podfile.lock
  src/lib/Components/Home/ArtistRails/ArtistCard.tsx
  src/lib/Components/Home/ArtistRails/__tests__/__snapshots__/ArtistCard-tests.tsx.snap
Labels: Merge On Green

#1766 [v2] Remove patch to surpress `__id` errors from graphql-js
  CHANGELOG.md
  patches/graphql+0.13.2.patch
Labels: Merge On Green

#1755 [Artwork view] Artwork commercial flow
  CHANGELOG.md
  Example/Emission/ARRootViewController.m
  Example/Emission/AppDelegate.m
  Example/Emission/UnroutedViewController.m
  data/complete.queryMap.json
  data/schema.graphql
  src/__generated__/ArtworkAvailability_artwork.graphql.ts
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/CommercialButtonsOfferOrderMutation.graphql.ts
  src/__generated__/CommercialButtonsOrderMutation.graphql.ts
  src/__generated__/CommercialButtonsTestsQuery.graphql.ts
  src/__generated__/CommercialButtons_artwork.graphql.ts
  src/__generated__/CommercialEditionSetInformation_artwork.graphql.ts
  src/__generated__/CommercialInformationSizeInfo_piece.graphql.ts
  src/__generated__/CommercialInformation_artwork.graphql.ts
  src/__generated__/CommercialPartnerInformation_artwork.graphql.ts
  src/__generated__/SellerInfo_artwork.graphql.ts
  src/lib/Scenes/Artwork/Components/ArtworkAvailability.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons.tsx
  src/lib/Scenes/Artwork/Components/CommercialEditionSetInformation.tsx
  src/lib/Scenes/Artwork/Components/CommercialInformation.tsx
  src/lib/Scenes/Artwork/Components/CommercialInformationSizeInfo.tsx
  src/lib/Scenes/Artwork/Components/CommercialPartnerInformation.tsx
  src/lib/Scenes/Artwork/Components/SellerInfo.tsx
  src/lib/Scenes/Artwork/Components/__stories__/ArtworkAvailability.story.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ArtworkAvailability-tests.tsx
  src/lib/Scenes/Artwork/Components/__tests__/CommercialButtons-tests.tsx
  src/lib/Scenes/Artwork/Components/__tests__/CommercialEditionSetInformation-tests.tsx
  src/lib/Scenes/Artwork/Components/__tests__/CommercialInformation-tests.tsx
  src/lib/Scenes/Artwork/Components/__tests__/SellerInfo-tests.tsx
  src/lib/relay/middlewares/metaphysicsMiddleware.ts
  storybook/storyLoader.js
Labels: Jira Synced

#1768 Fix copy on registration pending view
  CHANGELOG.md
  src/lib/Components/Bidding/Screens/RegistrationResult.tsx
  src/lib/Components/Bidding/Screens/__tests__/__snapshots__/RegistrationResult-tests.tsx.snap
Labels: Jira Synced, Merge On Green

#1769 PURCHASE-1309: Fixes mailto links rendered in markdown
  CHANGELOG.md
  Example/Podfile.lock
  src/lib/Components/Bidding/Screens/__tests__/RegistrationResult-tests.tsx
  src/lib/Components/__tests__/Markdown-tests.tsx
  src/lib/utils/renderMarkdown.tsx
Labels: Merge On Green

#1778 Configures auto release on merges to master
  .circleci/config.yml
  CHANGELOG.md
  OLD_CHANGELOG.md
  package.json
  scripts/release.js
  yarn.lock
Labels: Version: Patch

#1780 Fixing auto-release script take 2
  .circleci/config.yml
Labels: Version: Patch

#1781 Download pods from a cdn
  Example/Gemfile
  Example/Gemfile.lock
  Example/Podfile
  Example/Podfile.lock
Labels: Merge On Green, Version: Patch

#1788 [InfiniteScrollArtworksGrid] Small refactor cleanup
  src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
Labels: Merge On Green

#1789 [PURCHASE-1143] Removes artwork set functionality
  CHANGELOG.md
  Example/Emission/AppDelegate.m
  Pod/Classes/Core/ARSwitchBoardModule.h
  Pod/Classes/Core/ARSwitchBoardModule.m
  package.json
  src/lib/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/lib/Components/ArtworkGrids/GenericGrid.tsx
  src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/lib/NativeModules/SwitchBoard.tsx
Labels: Merge On Green

#1790 PURCHASE-1381 - Handle order mutation error
  src/lib/Scenes/Artwork/Components/CommercialButtons.tsx
Labels: Jira Synced, Merge On Green

#1786 [Consignments] Switch to use relay and fix query to use camelCase
  CHANGELOG.md
  data/complete.queryMap.json
  src/__generated__/ConsignmentsArtistQuery.graphql.ts
  src/lib/Components/Consignments/Components/SearchResults.tsx
  src/lib/Components/Consignments/Screens/ConsignmentsArtist.tsx
  src/lib/Components/Consignments/Screens/Overview.tsx
  src/lib/Components/Consignments/Screens/__tests__/ConsignmentsArtist-tests.tsx
  src/lib/Components/Consignments/Screens/__tests__/Overview-tests.tsx
  src/lib/Components/Consignments/__stories__/Consignments.story.tsx
Labels: Consignments, Jira Synced, Merge On Green

#1787 [City Guide] Fix clicking on single pin on map
  CHANGELOG.md
  src/lib/Scenes/Map/GlobalMap.tsx
Labels: Jira Synced

#1791 [Artwork View] Auction flow buttons
  CHANGELOG.md
  Example/Emission/ARRootViewController.m
  Example/Podfile.lock
  data/complete.queryMap.json
  data/schema.graphql
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/BidButtonTestsQuery.graphql.ts
  src/__generated__/BidButton_artwork.graphql.ts
  src/__generated__/BuyNowButtonOrderMutation.graphql.ts
  src/__generated__/BuyNowButton_artwork.graphql.ts
  src/__generated__/CommercialButtonsTestsMutationQuery.graphql.ts
  src/__generated__/CommercialButtonsTestsQuery.graphql.ts
  src/__generated__/CommercialButtonsTestsRenderQuery.graphql.ts
  src/__generated__/CommercialButtons_artwork.graphql.ts
  src/__generated__/MakeOfferButtonOrderMutation.graphql.ts
  src/__generated__/MakeOfferButton_artwork.graphql.ts
  src/lib/Scenes/Artwork/Components/CommercialButtons.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/BidButton.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/MakeOfferButton.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/BidButton-tests.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/CommercialButtons-tests.tsx
  src/lib/Scenes/Artwork/Components/CommercialInformation.tsx
  src/lib/Scenes/Artwork/Components/__tests__/CommercialInformation-tests.tsx
  src/lib/__fixtures__/ArtworkBidAction.ts
  src/lib/__fixtures__/ArtworkFixture.ts
Labels: Merge On Green

#1798 PURCHASE-1405 - [Artwork View] - Auction countdown
  CHANGELOG.md
  Example/Emission/ARRootViewController.m
  data/complete.queryMap.json
  package.json
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/AuctionCountDownTimer_artwork.graphql.ts
  src/__generated__/CommercialInformation_artwork.graphql.ts
  src/lib/Scenes/Artwork/Components/AuctionCountDownTimer.tsx
  src/lib/Scenes/Artwork/Components/CommercialInformation.tsx
  src/lib/Scenes/Artwork/Components/__tests__/AuctionCountDownTimer-tests.tsx
  src/lib/Scenes/Artwork/Components/__tests__/CommercialInformation-tests.tsx
  yarn.lock
Labels: Jira Synced, Merge On Green

#1793 PURCHASE-1383 - [Artwork view] - Additional links for FAQ and ask a specialist
  CHANGELOG.md
  data/complete.queryMap.json
  src/__generated__/ArtworkExtraLinks_artwork.graphql.ts
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/CommercialInformation_artwork.graphql.ts
  src/lib/Scenes/Artwork/Components/ArtworkExtraLinks.tsx
  src/lib/Scenes/Artwork/Components/CommercialInformation.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ArtworkExtraLinks-tests.tsx
Labels: Jira Synced

#1804 PURCHASE-1409 - Fixes ContextCard with new MPv2 typename field
  src/lib/Scenes/Artwork/Components/ContextCard.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ContextCard-tests.tsx
Labels: Jira Synced, Merge On Green

#1805 PURCHASE-1409: [RN Artwork View] Empty section on some artworks
  data/complete.queryMap.json
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/ContextCard_artwork.graphql.ts
  src/lib/Scenes/Artwork/Components/ContextCard.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ContextCard-tests.tsx
Labels: Jira Synced

#1806 Ensure filter selections don't automatically reset
  CHANGELOG.md
  src/lib/Components/FilteredInfiniteScrollGrid/Filters.tsx
Labels: Jira Synced

#1807 PURCHASE-1387 - Adds VAT included in price & replaces FilterArtworksConnection.count.internalID
  CHANGELOG.md
  data/complete.queryMap.json
  data/schema.graphql
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/CommercialPartnerInformation_artwork.graphql.ts
  src/__generated__/FairArtworksQuery.graphql.ts
  src/__generated__/FairArtworksTestsQuery.graphql.ts
  src/__generated__/FairBoothQuery.graphql.ts
  src/__generated__/FairBoothTestsQuery.graphql.ts
  src/__generated__/FilteredInfiniteScrollGridQuery.graphql.ts
  src/__generated__/Filters_filteredArtworks.graphql.ts
  src/__generated__/GeneQuery.graphql.ts
  src/__generated__/Gene_gene.graphql.ts
  src/__generated__/QueryRenderersGeneQuery.graphql.ts
  src/__generated__/ShowArtworksQuery.graphql.ts
  src/__generated__/ShowArtworksTestsQuery.graphql.ts
  src/lib/Components/FilteredInfiniteScrollGrid/Filters.tsx
  src/lib/Containers/Gene.tsx
  src/lib/Scenes/Artwork/Components/CommercialPartnerInformation.tsx
Labels: Jira Synced

#1808 Some follow-ups from a previous PR
  Example/Podfile.lock
  data/complete.queryMap.json
  src/__generated__/GeneQuery.graphql.ts
  src/__generated__/Gene_gene.graphql.ts
  src/__generated__/QueryRenderersGeneQuery.graphql.ts
  src/lib/Containers/Gene.tsx
  src/lib/NativeModules/triggerRefine.tsx
Labels: Merge On Green

#1809 Adds CommercialButton analytics
  src/lib/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/MakeOfferButton.tsx
  src/lib/utils/track/schema.ts
Labels: Merge On Green

#1797 Initial setup for Collection page
  CHANGELOG.md
  Example/Emission/ARRootViewController.m
  Pod/Classes/ViewControllers/ARCollectionComponentViewController.h
  Pod/Classes/ViewControllers/ARCollectionComponentViewController.m
  data/complete.queryMap.json
  src/__generated__/CollectionHeader_collection.graphql.ts
  src/__generated__/Collection_collection.graphql.ts
  src/__generated__/QueryRenderersCollectionQuery.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Scenes/Collection/Collection.tsx
  src/lib/Scenes/Collection/Components/CollectionHeader.tsx
  src/lib/Scenes/Collection/index.tsx
  src/lib/relay/QueryRenderers.tsx
Labels: Jira Synced

#1810 PURCHASE-1430, PURCHASE-1429, PURCHASE-1422: Tests and bug fixes
  data/complete.queryMap.json
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/CommercialPartnerInformation_artwork.graphql.ts
  src/lib/Scenes/Artwork/Components/AuctionCountDownTimer.tsx
  src/lib/Scenes/Artwork/Components/CommercialPartnerInformation.tsx
  src/lib/Scenes/Artwork/Components/__tests__/AuctionCountDownTimer-tests.tsx
  src/lib/Scenes/Artwork/Components/__tests__/CommercialInformation-tests.tsx
  src/lib/Scenes/Artwork/Components/__tests__/CommercialPartnerInformation-tests.tsx
Labels: Jira Synced

#1813 PLATFORM-1706/PURCHASE-1437: Fixes crash when Artist name tapped in Artist tab
  src/lib/Components/ArtistListItem.tsx
  src/lib/Components/WorksForYou/Notification.tsx
Labels: Jira Synced

#1816 PURCHASE-1407: Artwork dimensions distorted in view in room
  src/lib/Scenes/Artwork/Components/ArtworkActions.tsx
Labels: Jira Synced, Merge On Green

#1817 PURCHASE-1391 - Auction tombstone
  CHANGELOG.md
  Example/Emission/ARRootViewController.m
  data/complete.queryMap.json
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/ArtworkTombstoneStoryQuery.graphql.ts
  src/__generated__/ArtworkTombstone_artwork.graphql.ts
  src/lib/Scenes/Artwork/Components/ArtworkTombstone.tsx
  src/lib/Scenes/Artwork/Components/__stories__/ArtworkTombstone.story.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ArtworkTombstone-tests.tsx
Labels: Jira Synced, Merge On Green

#1819 PURCHASE-1436 - Small tombstone fix
  src/lib/Scenes/Artwork/Components/ArtworkTombstone.tsx
Labels: Jira Synced

#1820 PURCHASE-1434 - Small typography change
  src/lib/Scenes/Artwork/Components/ArtworkExtraLinks.tsx
  src/lib/Scenes/Artwork/Components/ArtworkTombstone.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ArtworkExtraLinks-tests.tsx
Labels: Jira Synced

#1822 [Core] Refactor screen dimensions to be dynamic.
  CHANGELOG.md
  Pod/Classes/Core/ARDynamicScreenDimensions.h
  Pod/Classes/Core/ARDynamicScreenDimensions.m
  Pod/Classes/Core/ARScrollViewHelpers.m
  Pod/Classes/Core/RNStaticSafeAreaInsets.h
  Pod/Classes/Core/RNStaticSafeAreaInsets.m
  package.json
  src/lib/Scenes/Artwork/Artwork.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/FullScreen/DeepZoom/DeepZoomLevel.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/FullScreen/DeepZoom/DeepZoomOverlay.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageCarouselCloseButton.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageCarouselFullScreen.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageZoomView.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/FullScreen/StatusBarOverlay.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/FullScreen/VerticalSwipeToDismiss.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/FullScreen/screen.ts
  src/lib/Scenes/Artwork/Components/ImageCarousel/FullScreen/useDoublePressCallback.ts
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarouselEmbedded.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/__tests__/ImageCarousel-tests.tsx
  src/lib/Scenes/Artwork/Components/__stories__/ArtworkTombstone.story.tsx
  src/lib/utils/screenSafeAreaInsets.ts
  src/lib/utils/useScreenDimensions.tsx
  src/setupJest.ts
Labels: Merge On Green

#1824 PURCHASE-1327 - Fixes analytic typing
  src/lib/Components/ArtistListItem.tsx
  src/lib/Components/ArtworkGrids/GenericGrid.tsx
  src/lib/Scenes/Artwork/Components/ArtworkDetails.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/MakeOfferButton.tsx
  src/lib/Scenes/Fair/Screens/FairBMWArtActivation.tsx
  src/lib/utils/track/schema.ts
Labels: Jira Synced

#1825 PURCHASE-1396 - Adds Buy Now button to artwork with isBuyNowable
  CHANGELOG.md
  Example/Emission/ARRootViewController.m
  data/complete.queryMap.json
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/BuyNowButton_artwork.graphql.ts
  src/__generated__/CommercialButtonsTestsMutationQuery.graphql.ts
  src/__generated__/CommercialButtonsTestsRenderQuery.graphql.ts
  src/__generated__/CommercialButtons_artwork.graphql.ts
  src/lib/Scenes/Artwork/Components/ArtworkExtraLinks.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/BuyNowButton.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/CommercialButtons-tests.tsx
  src/lib/__fixtures__/ArtworkFixture.ts
Labels: Jira Synced

#1827 Check for scrollview before scrolling
  src/lib/Components/ScrollableTabBar.tsx
Labels: Merge On Green
