Repository artsy/emission, pull requests merged in 2019-11, with the labels that each got.

#1951 Repalce bidAmountMinor with bidAmountCents
  data/complete.queryMap.json
  data/schema.graphql
  src/__generated__/PriceSummaryQuery.graphql.ts
  src/__generated__/PriceSummary_calculatedCost.graphql.ts
  src/lib/Components/Bidding/Screens/ConfirmBid/PriceSummary.tsx
Labels: Version: Patch

#1952 Adjust the loader position for <PriceSummary>
  CHANGELOG.md
  src/lib/Components/Bidding/Screens/ConfirmBid/PriceSummary.tsx
  src/lib/Components/Bidding/Screens/ConfirmBid/index.tsx
  src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmBid-tests.tsx.snap
Labels: Jira Synced, Version: Patch

#1950 [ME-37] Fixes iOS Share Sheet invocation
  src/lib/Scenes/Artwork/Components/ArtworkActions.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ArtworkActions-tests.tsx
Labels: Merge On Green, Version: Patch

#1957 Updates Extraction #trivial
  Example/Podfile.lock
Labels: Jira Synced, Version: Patch

#1958 [ME-83] Adds empty View Controller for upcoming Search work
  Example/Emission/ARRootViewController.m
  Pod/Classes/ViewControllers/ARSearchComponentViewController.h
  Pod/Classes/ViewControllers/ARSearchComponentViewController.m
  src/lib/AppRegistry.tsx
  src/lib/Scenes/Search/Search.tsx
  src/lib/Scenes/Search/__stories__/Search.story.tsx
  src/lib/Scenes/Search/index.tsx
  src/lib/utils/track/schema.ts
  storybook/storyLoader.js
Labels: Merge On Green, Version: Patch

#1959 AUCT-677 update buyer's premium copy
  Example/Emission/ARRootViewController.m
  src/lib/Scenes/Artwork/Components/AuctionPrice.tsx
Labels: Jira Synced, Version: Patch

#1963 hide artists list when no artists
  src/lib/Scenes/Partner/Components/PartnerOverview.tsx
Labels: Merge On Green, Version: Patch

#1964 Condenses partner header
  src/lib/Scenes/Partner/Components/PartnerHeader.tsx
Labels: Merge On Green, Version: Patch

#1945 Partner view tests
  .vscode/settings.json
  data/complete.queryMap.json
  src/__generated__/PartnerArtworkTestsQuery.graphql.ts
  src/__generated__/PartnerHeaderTestsQuery.graphql.ts
  src/__generated__/PartnerLocationSectionTestsQuery.graphql.ts
  src/__generated__/PartnerLocationsTestsQuery.graphql.ts
  src/__generated__/PartnerOverviewTestsQuery.graphql.ts
  src/__generated__/PartnerShowsTestsQuery.graphql.ts
  src/lib/Scenes/Partner/Components/PartnerArtwork.tsx
  src/lib/Scenes/Partner/Components/PartnerHeader.tsx
  src/lib/Scenes/Partner/Components/PartnerLocationSection.tsx
  src/lib/Scenes/Partner/Components/PartnerShowRailItem.tsx
  src/lib/Scenes/Partner/Components/PartnerShows.tsx
  src/lib/Scenes/Partner/Components/__fixtures__/PartnerArtwork-fixture.ts
  src/lib/Scenes/Partner/Components/__tests__/PartnerArtwork-tests.tsx
  src/lib/Scenes/Partner/Components/__tests__/PartnerHeader-tests.tsx
  src/lib/Scenes/Partner/Components/__tests__/PartnerLocationSection-tests.tsx
  src/lib/Scenes/Partner/Components/__tests__/PartnerOverview-tests.tsx
  src/lib/Scenes/Partner/Components/__tests__/PartnerShows-tests.tsx
  src/lib/Scenes/Partner/Components/__tests__/__snapshots__/PartnerArtwork-tests.tsx.snap
  src/lib/Scenes/Partner/Partner.tsx
  src/lib/Scenes/Partner/Screens/PartnerLocations.tsx
  src/lib/Scenes/Partner/Screens/__fixtures__/PartnerLocations-fixture.ts
  src/lib/Scenes/Partner/Screens/__tests__/PartnerLocations-tests.tsx
  src/lib/Scenes/Partner/Screens/__tests__/__snapshots__/PartnerLocations-tests.tsx.snap
Labels: Version: Patch

#1967 Fixes it(It...
  src/lib/Components/Consignments/Screens/__tests__/Confirmation-tests.tsx
  src/lib/Containers/__tests__/Inbox-tests.tsx
  src/lib/Scenes/Partner/Components/__tests__/PartnerArtwork-tests.tsx
  src/lib/Scenes/Partner/Components/__tests__/PartnerHeader-tests.tsx
  src/lib/Scenes/Partner/Components/__tests__/PartnerLocationSection-tests.tsx
  src/lib/Scenes/Partner/Components/__tests__/PartnerOverview-tests.tsx
  src/lib/Scenes/Partner/Components/__tests__/PartnerShows-tests.tsx
  src/lib/Scenes/Partner/Components/__tests__/__snapshots__/PartnerArtwork-tests.tsx.snap
  src/lib/Scenes/Partner/Screens/__tests__/PartnerLocations-tests.tsx
  src/lib/Scenes/Partner/Screens/__tests__/__snapshots__/PartnerLocations-tests.tsx.snap
Labels: Merge On Green, Version: Patch

#1968 Adds spinners to partner page
  src/lib/Scenes/Partner/Components/PartnerArtwork.tsx
  src/lib/Scenes/Partner/Components/PartnerOverview.tsx
  src/lib/Scenes/Partner/Components/PartnerShows.tsx
Labels: Merge On Green, Version: Patch

#1966 ME-86 Search Autosuggest
  data/complete.queryMap.json
  src/__generated__/AutosuggestResultsQuery.graphql.ts
  src/lib/Scenes/Search/AutosuggestResults.tsx
  src/lib/Scenes/Search/Input.tsx
  src/lib/Scenes/Search/Search.tsx
  src/lib/Scenes/Search/__tests__/AutosuggestResults-tests.tsx
  src/lib/Scenes/Search/__tests__/Search-tests.tsx
  src/lib/utils/CatchErrors.tsx
Labels: Jira Synced, Version: Patch

#1969 Partner updates
  data/complete.queryMap.json
  src/__generated__/PartnerLocationSectionTestsQuery.graphql.ts
  src/__generated__/PartnerLocationSection_partner.graphql.ts
  src/__generated__/PartnerOverviewInfiniteScrollQuery.graphql.ts
  src/__generated__/PartnerOverviewTestsQuery.graphql.ts
  src/__generated__/PartnerQuery.graphql.ts
  src/__generated__/PartnerRefetchQuery.graphql.ts
  src/lib/Scenes/Partner/Components/PartnerArtwork.tsx
  src/lib/Scenes/Partner/Components/PartnerFollowButton.tsx
  src/lib/Scenes/Partner/Components/PartnerHeader.tsx
  src/lib/Scenes/Partner/Components/PartnerLocationSection.tsx
  src/lib/Scenes/Partner/Components/PartnerOverview.tsx
  src/lib/Scenes/Partner/Components/PartnerShows.tsx
  src/lib/Scenes/Partner/Components/__tests__/PartnerLocationSection-tests.tsx
  src/lib/Scenes/Partner/Components/__tests__/PartnerOverview-tests.tsx
Labels: Merge On Green, Version: Patch

#1971 Collection Header
  data/complete.queryMap.json
  src/__generated__/CollectionHeader_collection.graphql.ts
  src/__generated__/QueryRenderersCollectionQuery.graphql.ts
  src/lib/Scenes/Collection/Collection.tsx
  src/lib/Scenes/Collection/Components/CollectionHeader.tsx
  src/lib/Scenes/Collection/Components/__fixtures__/index.ts
  src/lib/Scenes/Collection/Components/__tests__/CollectionHeader-tests.tsx
  src/lib/Scenes/Collection/Components/__tests__/__snapshots__/CollectionHeader-tests.tsx.snap
  src/lib/Scenes/Collection/__tests__/Collection-tests.tsx
  src/lib/Scenes/Collection/__tests__/__snapshots__/Collection-tests.tsx.snap
Labels: Jira Synced, Version: Patch

#1974 Sticky tab collapsing header
  Example/Podfile
  Example/Podfile.lock
  package.json
  src/lib/Components/StickyTabPage/SnappyHorizontalRail.tsx
  src/lib/Components/StickyTabPage/StickyTabPage.tsx
  src/lib/Components/StickyTabPage/StickyTabScrollView.tsx
  src/lib/Components/StickyTabPage/reanimatedHelpers.ts
  src/lib/Scenes/Partner/Components/PartnerArtwork.tsx
  src/lib/Scenes/Partner/Components/PartnerOverview.tsx
  src/lib/Scenes/Partner/Components/PartnerShows.tsx
  src/lib/Scenes/Partner/Components/__tests__/PartnerArtwork-tests.tsx
  src/lib/Scenes/Partner/Components/__tests__/PartnerOverview-tests.tsx
  src/lib/Scenes/Partner/Components/__tests__/PartnerShows-tests.tsx
  src/lib/Scenes/Partner/Components/__tests__/__snapshots__/PartnerArtwork-tests.tsx.snap
  src/lib/Scenes/Partner/Partner.tsx
  src/lib/utils/isCloseToBottom.ts
  src/setupJest.ts
  yarn.lock
Labels: Version: Patch

#1976 ME-110 - Partner QA
  data/complete.queryMap.json
  src/__generated__/PartnerOverviewInfiniteScrollQuery.graphql.ts
  src/__generated__/PartnerOverview_partner.graphql.ts
  src/__generated__/PartnerQuery.graphql.ts
  src/__generated__/PartnerRefetchQuery.graphql.ts
  src/lib/Components/StickyTabPage/StickyTabScrollView.tsx
  src/lib/Scenes/Partner/Components/PartnerFollowButton.tsx
  src/lib/Scenes/Partner/Components/PartnerHeader.tsx
  src/lib/Scenes/Partner/Components/PartnerLocationSection.tsx
  src/lib/Scenes/Partner/Components/PartnerOverview.tsx
  src/lib/Scenes/Partner/Components/PartnerShows.tsx
  src/lib/Scenes/Partner/Components/__tests__/PartnerOverview-tests.tsx
  src/lib/Scenes/Partner/Partner.tsx
  src/lib/Scenes/Partner/Screens/PartnerLocations.tsx
  src/lib/Scenes/Partner/Screens/__tests__/__snapshots__/PartnerLocations-tests.tsx.snap
Labels: Jira Synced, Version: Patch

#1978 Adds sort to Partner.artworks
  data/complete.queryMap.json
  src/__generated__/PartnerArtworkInfiniteScrollGridQuery.graphql.ts
  src/__generated__/PartnerArtwork_partner.graphql.ts
  src/__generated__/PartnerQuery.graphql.ts
  src/__generated__/PartnerRefetchQuery.graphql.ts
  src/lib/Scenes/Partner/Components/PartnerArtwork.tsx
Labels: Merge On Green, Version: Patch

#1979 Small cleanup of unused code
  Example/Emission/ARRootViewController.m
  src/lib/Scenes/Partner/Components/PartnerOverview.tsx
  src/lib/Scenes/Partner/Partner.tsx
Labels: Merge On Green, Version: Patch

#1980 Fixes an issue where the feature flag of '0' causes a crash
  src/lib/Components/Bidding/Screens/ConfirmBid/index.tsx
Labels: Version: Patch
