Repository artsy/emission, pull requests merged in 2019-03, with the labels that each got.

#1369 Ensures the map is full bleed inside Eigen
  CHANGELOG.md
  Pod/Classes/ViewControllers/ARMapComponentViewController.m
  package.json
Labels: Merge On Green

#1374 City picker ld 162
  CHANGELOG.md
  src/lib/Icons/CircleWhiteCheckIcon.tsx
  src/lib/Scenes/City/City.tsx
  src/lib/Scenes/City/CityPicker.tsx
Labels: Jira Synced, Merge On Green

#1377 Shows city picker modal
  CHANGELOG.md
  Example/Podfile.lock
  Pod/Classes/Data/ARCity.h
  Pod/Classes/Data/ARCity.m
  Pod/Classes/ViewControllers/ARCityPickerComponentViewController.h
  Pod/Classes/ViewControllers/ARCityPickerComponentViewController.m
  Pod/Classes/ViewControllers/ARMapContainerViewController.m
  package.json
  scripts/generate-cities-objc.ts
  src/lib/AppRegistry.tsx
  src/lib/Scenes/City/City.tsx
  src/lib/Scenes/City/CityPicker.tsx
  src/lib/Scenes/City/Components/AllEvents.tsx
  src/lib/Scenes/City/cities.ts
  src/lib/Scenes/Map/Components/CitySwitcherButton.tsx
  src/lib/Scenes/Map/GlobalMap.tsx
  src/lib/Scenes/Map/MapContainer.tsx
  src/lib/Scenes/Map/MapRenderer.tsx
  yarn.lock
Labels: Jira Synced

#1372 Show favorite artists in the list of participating artists first
  CHANGELOG.md
  src/__generated__/FairDetailShowsQuery.graphql.ts
  src/__generated__/FairDetailShowsQuery.queryMap.json
  src/__generated__/FairDetailTestsQuery.graphql.ts
  src/__generated__/FairDetailTestsQuery.queryMap.json
  src/__generated__/FairHeader_fair.graphql.ts
  src/__generated__/FairQuery.graphql.ts
  src/__generated__/FairQuery.queryMap.json
  src/__generated__/FairTestsQuery.graphql.ts
  src/__generated__/FairTestsQuery.queryMap.json
  src/__generated__/QueryRenderersFairQuery.graphql.ts
  src/__generated__/QueryRenderersFairQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/__generated__/indexTestsFairHeaderQuery.graphql.ts
  src/__generated__/indexTestsFairHeaderQuery.queryMap.json
  src/lib/Scenes/Fair/Components/FairHeader/index.tsx
Labels: Jira Synced, Merge On Green

#1380 Fixes render failure with missing city coords.
  CHANGELOG.md
  src/lib/Scenes/Map/MapContainer.tsx
Labels: Jira Synced

#1376 City tabs styling
  CHANGELOG.md
  src/lib/Components/Buttons/InvertedButton.tsx
  src/lib/Components/Lists/SavedShowItemRow.tsx
  src/lib/Scenes/City/Components/EventSection/index.tsx
  src/lib/Scenes/City/Components/SavedEventSection/index.tsx
Labels: Merge On Green

#1384 Remembers users' city selections
  CHANGELOG.md
  Pod/Classes/ViewControllers/ARCityPickerComponentViewController.h
  Pod/Classes/ViewControllers/ARCityPickerComponentViewController.m
  Pod/Classes/ViewControllers/ARMapContainerViewController.m
  src/lib/Scenes/City/CityPicker.tsx
  src/lib/Scenes/City/Components/Event/index.tsx
Labels: Jira Synced

#1378 Adds BMW art guide to All events sections
  CHANGELOG.md
  src/lib/Scenes/City/Components/AllEvents.tsx
  src/lib/Scenes/City/Components/BMWEventSection/__tests__/index-tests.tsx
  src/lib/Scenes/City/Components/BMWEventSection/index.tsx
Labels: Merge On Green

#1386 Fetch all city shows and fairs
  data/schema.graphql
  src/__generated__/GlobalMapRefetchQuery.graphql.ts
  src/__generated__/GlobalMapRefetchQuery.queryMap.json
  src/__generated__/GlobalMapTestsQuery.graphql.ts
  src/__generated__/GlobalMapTestsQuery.queryMap.json
  src/__generated__/GlobalMap_viewer.graphql.ts
  src/__generated__/MapRendererQuery.graphql.ts
  src/__generated__/MapRendererQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/lib/Components/Lists/SavedShowItemRow.tsx
  src/lib/Scenes/Map/GlobalMap.tsx
  src/lib/Scenes/Map/MapRenderer.tsx
  src/lib/Scenes/Map/__tests__/GlobalMap-tests.tsx
Labels: Jira Synced

#1371 LD-304 - Uses exhibition_period from MP for date ranges
  CHANGELOG.md
  data/schema.graphql
  src/__generated__/EventSectionTestsQuery.graphql.ts
  src/__generated__/EventSectionTestsQuery.queryMap.json
  src/__generated__/EventSection_event.graphql.ts
  src/__generated__/FairDetailShowsQuery.graphql.ts
  src/__generated__/FairDetailShowsQuery.queryMap.json
  src/__generated__/FairDetailTestsQuery.graphql.ts
  src/__generated__/FairDetailTestsQuery.queryMap.json
  src/__generated__/FairHeader_fair.graphql.ts
  src/__generated__/FairQuery.graphql.ts
  src/__generated__/FairQuery.queryMap.json
  src/__generated__/FairTestsQuery.graphql.ts
  src/__generated__/FairTestsQuery.queryMap.json
  src/__generated__/FairsQuery.graphql.ts
  src/__generated__/FairsQuery.queryMap.json
  src/__generated__/Fairs_me.graphql.ts
  src/__generated__/FavoriteFairsQuery.graphql.ts
  src/__generated__/FavoriteFairsQuery.queryMap.json
  src/__generated__/FavoriteShowsQuery.graphql.ts
  src/__generated__/FavoriteShowsQuery.queryMap.json
  src/__generated__/GlobalMapRefetchQuery.graphql.ts
  src/__generated__/GlobalMapRefetchQuery.queryMap.json
  src/__generated__/GlobalMapTestsQuery.graphql.ts
  src/__generated__/GlobalMapTestsQuery.queryMap.json
  src/__generated__/GlobalMap_viewer.graphql.ts
  src/__generated__/MapRendererQuery.graphql.ts
  src/__generated__/MapRendererQuery.queryMap.json
  src/__generated__/MoreInfoTestsQuery.graphql.ts
  src/__generated__/MoreInfoTestsQuery.queryMap.json
  src/__generated__/MoreInfo_show.graphql.ts
  src/__generated__/QueryRenderersFairQuery.graphql.ts
  src/__generated__/QueryRenderersFairQuery.queryMap.json
  src/__generated__/QueryRenderersShowMoreInfoQuery.graphql.ts
  src/__generated__/QueryRenderersShowMoreInfoQuery.queryMap.json
  src/__generated__/QueryRenderersShowQuery.graphql.ts
  src/__generated__/QueryRenderersShowQuery.queryMap.json
  src/__generated__/SavedShowItemRow_show.graphql.ts
  src/__generated__/ShowQuery.graphql.ts
  src/__generated__/ShowQuery.queryMap.json
  src/__generated__/ShowTestsQuery.graphql.ts
  src/__generated__/ShowTestsQuery.queryMap.json
  src/__generated__/ShowsQuery.graphql.ts
  src/__generated__/ShowsQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/__generated__/indexTestsFairHeaderQuery.graphql.ts
  src/__generated__/indexTestsFairHeaderQuery.queryMap.json
  src/lib/Components/Lists/SavedFairItemRow.tsx
  src/lib/Components/Lists/SavedShowItemRow.tsx
  src/lib/Scenes/City/Components/Event/__tests__/index-tests.tsx
  src/lib/Scenes/City/Components/Event/index.tsx
  src/lib/Scenes/City/Components/FairEventSection/Components/FairEventSectionCard.tsx
  src/lib/Scenes/City/Components/TabFairItemRow/index.tsx
  src/lib/Scenes/Fair/Components/FairHeader/index.tsx
  src/lib/Scenes/Favorites/Components/Fairs/index.tsx
  src/lib/Scenes/Map/GlobalMap.tsx
  src/lib/Scenes/Show/Components/EventSection.tsx
  src/lib/Scenes/Show/Components/__tests__/EventSection-tests.tsx
  src/lib/Scenes/Show/Screens/MoreInfo.tsx
Labels: Jira Synced

#1391 LD-323 - All event section events now link to show
  CHANGELOG.md
  src/lib/Scenes/City/Components/Event/index.tsx
  src/lib/Scenes/City/Components/EventSection/index.tsx
  src/lib/Scenes/City/Components/FairEventSection/__tests__/index-tests.tsx
  src/lib/Scenes/City/Components/FairEventSection/index.tsx
Labels: Jira Synced

#1387 Adds styling/sizing based on screen size to contents of CityPicker modal
  CHANGELOG.md
  src/lib/Scenes/City/CityPicker.tsx
  src/lib/data/ScreenSizes/screenSizes.tsx
Labels: Jira Synced

#1392 Default show icon
  CHANGELOG.md
  src/lib/Components/Lists/SavedShowItemRow.tsx
  src/lib/Icons/Pin.tsx
Labels: Jira Synced

#1390 Fixes rounded corners on city picker component
  CHANGELOG.md
  Pod/Classes/ViewControllers/ARMapContainerViewController.m
Labels: Jira Synced, Merge On Green

#1382 Add followedContent to show query to get list of followed artists and…
  CHANGELOG.md
  data/schema.graphql
  src/__generated__/DetailTestsQuery.graphql.ts
  src/__generated__/DetailTestsQuery.queryMap.json
  src/__generated__/QueryRenderersShowQuery.graphql.ts
  src/__generated__/QueryRenderersShowQuery.queryMap.json
  src/__generated__/ShowHeader_show.graphql.ts
  src/__generated__/ShowQuery.graphql.ts
  src/__generated__/ShowQuery.queryMap.json
  src/__generated__/ShowTestsQuery.graphql.ts
  src/__generated__/ShowTestsQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/lib/Scenes/Fair/Components/FairHeader/index.tsx
  src/lib/Scenes/Show/Components/ShowHeader/ShowHeader.tsx
Labels: Merge On Green

#1395 LD-324 - Fixes link to fair in TabFairItemRow
  src/lib/Scenes/City/Components/TabFairItemRow/index.tsx
Labels: Jira Synced, Merge On Green

#1397 Fix the deploy script when the metaphysics changes are a NOOP
  scripts/merge-graphql-query-map.js
Labels: Merge On Green

#1400 Remove log
  src/lib/Scenes/City/City.tsx
Labels: Merge On Green

#1399 City QA
  CHANGELOG.md
  src/lib/Scenes/City/Components/BMWEventSection/index.tsx
  src/lib/Scenes/City/Components/EventSection/index.tsx
  src/lib/Scenes/City/Components/FairEventSection/index.tsx
  src/lib/Scenes/Map/Bucket.ts
Labels: Jira Synced

#1398 Show 3 artists instead of 2 in an entity list
  src/lib/Scenes/Fair/Components/FairHeader/index.tsx
  src/lib/Scenes/Show/Components/ShowHeader/ShowHeader.tsx
  src/lib/Scenes/Show/Components/ShowHeader/__tests__/__snapshots__/ShowHeader-tests.tsx.snap
Labels: Jira Synced

#1401 Improvements to city picker UX
  CHANGELOG.md
  Example/Podfile.lock
  Pod/Classes/ViewControllers/ARMapContainerViewController.m
  package.json
  src/lib/Scenes/City/City.tsx
  src/lib/Scenes/Map/Bucket.ts
  src/lib/Scenes/Map/GlobalMap.tsx
  src/lib/Scenes/Map/MapContainer.tsx
  src/lib/Scenes/Map/MapRenderer.tsx
Labels: Jira Synced

#1394 Adds BMW sponsoredContent to all events in city view
  CHANGELOG.md
  data/schema.graphql
  src/__generated__/GlobalMapTestsQuery.graphql.ts
  src/__generated__/GlobalMapTestsQuery.queryMap.json
  src/__generated__/GlobalMap_viewer.graphql.ts
  src/__generated__/MapRendererQuery.graphql.ts
  src/__generated__/MapRendererQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/lib/Scenes/City/City.tsx
  src/lib/Scenes/City/Components/AllEvents.tsx
  src/lib/Scenes/City/Components/BMWEventSection/__tests__/index-tests.tsx
  src/lib/Scenes/City/Components/BMWEventSection/index.tsx
  src/lib/Scenes/Map/GlobalMap.tsx
Labels: Merge On Green

#1402 Adds new view controller and path to expose bmw art activations content
  .circleci/config.yml
  CHANGELOG.md
  Example/Emission/AppDelegate.m
  Pod/Classes/ViewControllers/ARFairBMWArtActivationComponentViewController.h
  Pod/Classes/ViewControllers/ARFairBMWArtActivationComponentViewController.m
  data/schema.graphql
  src/__generated__/FairBMWArtActivationQuery.graphql.ts
  src/__generated__/FairBMWArtActivationQuery.queryMap.json
  src/__generated__/FairBMWArtActivationTestsQuery.graphql.ts
  src/__generated__/FairBMWArtActivationTestsQuery.queryMap.json
  src/__generated__/FairDetailShowsQuery.graphql.ts
  src/__generated__/FairDetailShowsQuery.queryMap.json
  src/__generated__/FairDetailTestsQuery.graphql.ts
  src/__generated__/FairDetailTestsQuery.queryMap.json
  src/__generated__/FairDetail_fair.graphql.ts
  src/__generated__/FairQuery.graphql.ts
  src/__generated__/FairQuery.queryMap.json
  src/__generated__/FairTestsQuery.graphql.ts
  src/__generated__/FairTestsQuery.queryMap.json
  src/__generated__/QueryRenderersFairQuery.graphql.ts
  src/__generated__/QueryRenderersFairQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/lib/AppRegistry.tsx
  src/lib/Scenes/Fair/Screens/FairBMWArtActivation.tsx
  src/lib/Scenes/Fair/Screens/FairDetail.tsx
  src/lib/Scenes/Fair/Screens/FairMoreInfo.tsx
  src/lib/Scenes/Fair/Screens/__tests__/FairBMWArtActivation-tests.tsx
  src/lib/Scenes/Fair/__fixtures__/index.ts
  src/lib/Scenes/Fair/index.ts
  src/lib/utils/track.ts
Labels: Jira Synced

#1411 [EventEmitter] Add unsubscribing capabilities.
  CHANGELOG.md
  Example/Podfile.lock
  src/lib/Scenes/City/City.tsx
  src/lib/Scenes/Map/EventEmitter.ts
  src/lib/Scenes/Map/GlobalMap.tsx
Labels: Jira Synced

#1413 LD-377 - Fixes console error about textAlign
  src/lib/Scenes/City/Components/CityTab.tsx
Labels: Jira Synced, Merge On Green

#1415 Styles cards for clusters pins and clusters
  CHANGELOG.md
  src/lib/Components/Lists/ShowItemRow.tsx
  src/lib/Scenes/Map/Components/ShowCard.tsx
  src/lib/Scenes/Map/GlobalMap.tsx
Labels: Merge On Green

#1417 [CityTab] Increase FlatList’s window size to avoid blank views.
  CHANGELOG.md
  src/lib/Scenes/City/Components/CityTab.tsx
Labels: Jira Synced

#1412 Fixes scroll view getting stuck
  CHANGELOG.md
  Example/Podfile.lock
  Pod/Classes/ViewControllers/ARMapContainerViewController.m
  package.json
  src/lib/Scenes/City/City.tsx
  src/lib/Scenes/City/Components/FairEventSection/Components/FairEventSectionCard.tsx
Labels: Jira Synced

#1385 CitySectionList
  .circleci/config.yml
  CHANGELOG.md
  Example/Emission/AppDelegate.m
  Pod/Classes/ViewControllers/ARCitySectionListComponentViewController.h
  Pod/Classes/ViewControllers/ARCitySectionListComponentViewController.m
  data/schema.graphql
  package.json
  src/__generated__/CitySectionListQuery.graphql.ts
  src/__generated__/CitySectionListQuery.queryMap.json
  src/__generated__/CitySectionList_city.graphql.ts
  src/__generated__/GlobalMapTestsQuery.graphql.ts
  src/__generated__/GlobalMapTestsQuery.queryMap.json
  src/__generated__/GlobalMap_viewer.graphql.ts
  src/__generated__/MapRendererQuery.graphql.ts
  src/__generated__/MapRendererQuery.queryMap.json
  src/__generated__/QueryRenderersCitySectionListQuery.graphql.ts
  src/__generated__/QueryRenderersCitySectionListQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/lib/AppRegistry.tsx
  src/lib/Containers/__tests__/index-tests.tsx
  src/lib/Containers/index.tsx
  src/lib/Scenes/City/City.tsx
  src/lib/Scenes/City/CitySectionList.tsx
  src/lib/Scenes/City/Components/AllEvents.tsx
  src/lib/Scenes/City/Components/EventList.tsx
  src/lib/Scenes/City/Components/EventSection/__tests__/index-tests.tsx
  src/lib/Scenes/City/Components/EventSection/index.tsx
  src/lib/Scenes/Map/GlobalMap.tsx
  src/lib/relay/QueryRenderers.tsx
Labels: Jira Synced

#1393 CityFairList
  .circleci/config.yml
  CHANGELOG.md
  Example/Emission/AppDelegate.m
  Example/Podfile.lock
  Pod/Classes/ViewControllers/ARCityFairListComponentViewController.h
  Pod/Classes/ViewControllers/ARCityFairListComponentViewController.m
  src/__generated__/CityFairListQuery.graphql.ts
  src/__generated__/CityFairListQuery.queryMap.json
  src/__generated__/CityFairList_city.graphql.ts
  src/__generated__/QueryRenderersCityFairListQuery.graphql.ts
  src/__generated__/QueryRenderersCityFairListQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/lib/AppRegistry.tsx
  src/lib/Components/Buttons/CaretButton.tsx
  src/lib/Containers/__tests__/index-tests.tsx
  src/lib/Containers/index.tsx
  src/lib/Scenes/City/CityFairList.tsx
  src/lib/Scenes/City/Components/AllEvents.tsx
  src/lib/Scenes/City/Components/FairEventSection/index.tsx
  src/lib/relay/QueryRenderers.tsx
Labels: Merge On Green

#1422 City picker cleanup
  CHANGELOG.md
  src/lib/Scenes/City/CityPicker.tsx
  src/lib/data/ScreenSizes/screenSizes.tsx
Labels: Jira Synced

#1424 Hook up save functionality to show card
  CHANGELOG.md
  images/MapBG.png
  src/lib/Components/Lists/ShowItemRow.tsx
  src/lib/Scenes/Map/Components/ShowCard.tsx
  src/lib/Scenes/Map/GlobalMap.tsx
Labels: Merge On Green

#1423 Map & city analytics v1.0
  CHANGELOG.md
  Pod/Classes/ViewControllers/ARMapContainerViewController.m
  src/lib/Components/Lists/ShowItemRow.tsx
  src/lib/Scenes/City/City.tsx
  src/lib/Scenes/City/CityPicker.tsx
  src/lib/Scenes/City/Components/AllEvents.tsx
  src/lib/Scenes/City/Components/BMWEventSection/__tests__/index-tests.tsx
  src/lib/Scenes/City/Components/BMWEventSection/index.tsx
  src/lib/Scenes/City/Components/Event/index.tsx
  src/lib/Scenes/City/__tests__/City-tests.tsx
  src/lib/Scenes/Fair/Screens/FairBMWArtActivation.tsx
  src/lib/Scenes/Map/GlobalMap.tsx
  src/lib/utils/track.ts
Labels: Jira Synced, Merge On Green

#1431 Adds iconOffset to pins on map
  src/lib/Scenes/Map/GlobalMap.tsx
Labels: Merge On Green

#1433 Project graphql map location
  Example/Podfile
  Example/Pods/Pods.xcodeproj/project.pbxproj
Labels: Merge On Green

#1436 [City] Use data from authoritative upstream source
  Example/Podfile.lock
  data/cityDataSortedByDisplayPreference.json
  package.json
  scripts/generate-cities-objc.js
  src/lib/Components/Artist/Shows/SmallList.tsx
  src/lib/Components/Bidding/Screens/BidResult.tsx
  src/lib/Components/Countdown/StateManager.tsx
  src/lib/Scenes/City/CityPicker.tsx
  src/lib/Scenes/City/cities.ts
  src/lib/Scenes/Map/__stories__/Map.story.tsx
  tsconfig.json
  yarn.lock
Labels: Jira Synced

#1438 Fixes fair list crash
  data/schema.graphql
  src/lib/Components/Lists/SavedFairItemRow.tsx
  src/lib/Scenes/City/CityFairList.tsx
  src/lib/Scenes/City/Components/TabFairItemRow/index.tsx
Labels: Merge On Green

#1435 Select pin ld67
  CHANGELOG.md
  src/lib/Icons/PinSavedOn.tsx
  src/lib/Icons/PinSavedSelected.tsx
  src/lib/Scenes/Map/GlobalMap.tsx
Labels: Jira Synced

#1396 CityBMWList
  .circleci/config.yml
  CHANGELOG.md
  Example/Emission/AppDelegate.m
  Example/Podfile.lock
  Example/Pods/Pods.xcodeproj/project.pbxproj
  Pod/Classes/ViewControllers/ARCityBMWListComponentViewController.h
  Pod/Classes/ViewControllers/ARCityBMWListComponentViewController.m
  package.json
  src/__generated__/CityBMWListQuery.graphql.ts
  src/__generated__/CityBMWListQuery.queryMap.json
  src/__generated__/CityBMWList_city.graphql.ts
  src/__generated__/GlobalMapTestsQuery.graphql.ts
  src/__generated__/GlobalMapTestsQuery.queryMap.json
  src/__generated__/GlobalMap_viewer.graphql.ts
  src/__generated__/MapRendererQuery.graphql.ts
  src/__generated__/MapRendererQuery.queryMap.json
  src/__generated__/QueryRenderersCityBMWListQuery.graphql.ts
  src/__generated__/QueryRenderersCityBMWListQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/lib/AppRegistry.tsx
  src/lib/Containers/__tests__/index-tests.tsx
  src/lib/Containers/index.tsx
  src/lib/Scenes/City/CityPicker.tsx
  src/lib/Scenes/City/Components/AllEvents.tsx
  src/lib/Scenes/City/Components/BMWEventSection/__tests__/index-tests.tsx
  src/lib/Scenes/City/Components/BMWEventSection/index.tsx
  src/lib/Scenes/City/Components/CityBMWList.tsx
  src/lib/Scenes/City/Components/EventList.tsx
  src/lib/Scenes/Map/GlobalMap.tsx
  src/lib/relay/QueryRenderers.tsx
Labels: Jira Synced, Merge On Green

#1444 Don't allow the map to rotate
  CHANGELOG.md
  Pod/Classes/ViewControllers/ARMapContainerViewController.m
Labels: Merge On Green

#1447 Add ability to pre-heat GraphQL cache and include cached City data
  CHANGELOG.md
  Emission.podspec
  Example/Emission.xcodeproj/project.pbxproj
  Example/Podfile.lock
  Example/Pods/Pods.xcodeproj/project.pbxproj
  Pod/Assets/PreHeatedGraphQLCache/MapRendererQuery-berlin-germany.json
  Pod/Assets/PreHeatedGraphQLCache/MapRendererQuery-hong-kong-hong-kong.json
  Pod/Assets/PreHeatedGraphQLCache/MapRendererQuery-london-united-kingdom.json
  Pod/Assets/PreHeatedGraphQLCache/MapRendererQuery-los-angeles-ca-usa.json
  Pod/Assets/PreHeatedGraphQLCache/MapRendererQuery-new-york-ny-usa.json
  Pod/Assets/PreHeatedGraphQLCache/MapRendererQuery-paris-france.json
  Pod/Classes/GraphQL/ARGraphQLQueryCache.m
  package.json
  scripts/generate-cities-cache.js
  scripts/generate-graphql-query-map.js
  scripts/queryMap.js
  src/lib/Scenes/Map/MapRenderer.tsx
Labels: Jira Synced, Merge On Green

#1446 Don't crash when clicking on a fair
  src/lib/Scenes/City/Components/TabFairItemRow/index.tsx
Labels: Merge On Green

#1439 Removes duplicate image #trivial
  Pod/Assets/assets/Pod/Assets/assets/images/BMW-logo.jpg
Labels: Merge On Green

#1448 Skips native CI when not files have been changed #trivial
  .circleci/config.yml
  package.json
  scripts/ci-skip-native-if-possible.js
  scripts/generate-cities-objc.js
Labels: Merge On Green

#1455 [GraphQL] Add freshness to pre-heated cache.
  .vscode/settings.json
  CHANGELOG.md
  Example/Podfile.lock
  Pod/Assets/PreHeatedGraphQLCache/MapRendererQuery-berlin-germany.json
  Pod/Assets/PreHeatedGraphQLCache/MapRendererQuery-hong-kong-hong-kong.json
  Pod/Assets/PreHeatedGraphQLCache/MapRendererQuery-london-united-kingdom.json
  Pod/Assets/PreHeatedGraphQLCache/MapRendererQuery-los-angeles-ca-usa.json
  Pod/Assets/PreHeatedGraphQLCache/MapRendererQuery-new-york-ny-usa.json
  Pod/Assets/PreHeatedGraphQLCache/MapRendererQuery-paris-france.json
  Pod/Classes/GraphQL/ARGraphQLQueryCache.m
  scripts/generate-cities-cache.js
  scripts/preheatGraphQLCache.js
Labels: Jira Synced, Merge On Green

#1452 Updates is_local_discovery to isStubShow to conditionally disable nav to Partner page
  CHANGELOG.md
  data/schema.graphql
  src/__generated__/DetailTestsQuery.graphql.ts
  src/__generated__/DetailTestsQuery.queryMap.json
  src/__generated__/QueryRenderersShowQuery.graphql.ts
  src/__generated__/QueryRenderersShowQuery.queryMap.json
  src/__generated__/ShowHeader_show.graphql.ts
  src/__generated__/ShowQuery.graphql.ts
  src/__generated__/ShowQuery.queryMap.json
  src/__generated__/ShowTestsQuery.graphql.ts
  src/__generated__/ShowTestsQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/lib/Scenes/Show/Components/ShowHeader/ShowHeader.tsx
Labels: Jira Synced

#1458 Fix the changelog
  CHANGELOG.md
Labels: Merge On Green

#1453 Fix bugs with cluster card carousel
  src/lib/Scenes/Map/Components/ShowCard.tsx
Labels: Jira Synced

#1454 City Map Pin SVG fixes
  CHANGELOG.md
  Example/Podfile.lock
  src/lib/Icons/PinFairSelected.tsx
  src/lib/Icons/PinSavedOn.tsx
  src/lib/Scenes/City/Components/SavedEventSection/index.tsx
  src/lib/Scenes/Favorites/index.tsx
  src/lib/Scenes/Map/GlobalMap.tsx
  src/lib/Scenes/Map/types.ts
Labels: Jira Synced, Merge On Green

#1466 [Map] Make user indicator purple.
  CHANGELOG.md
  Emission.podspec
  Example/Podfile.lock
  Example/Pods/Pods.xcodeproj/project.pbxproj
  Pod/Classes/ViewControllers/ARMapComponentViewController.m
  package.json
Labels: Jira Synced, Merge On Green

#1469 [GraphQL] Make pre-heated cache work for upgraders
  CHANGELOG.md
  Example/Podfile.lock
  Pod/Assets/PreHeatedGraphQLCache/MapRendererQuery-berlin-germany.json
  Pod/Assets/PreHeatedGraphQLCache/MapRendererQuery-hong-kong-hong-kong.json
  Pod/Assets/PreHeatedGraphQLCache/MapRendererQuery-london-united-kingdom.json
  Pod/Assets/PreHeatedGraphQLCache/MapRendererQuery-los-angeles-ca-usa.json
  Pod/Assets/PreHeatedGraphQLCache/MapRendererQuery-new-york-ny-usa.json
  Pod/Assets/PreHeatedGraphQLCache/MapRendererQuery-paris-france.json
  Pod/Classes/GraphQL/ARGraphQLQueryCache.m
Labels: Jira Synced

#1460 Removes user location button when user hasn't supplied location
  CHANGELOG.md
  src/lib/Scenes/Map/GlobalMap.tsx
Labels: Jira Synced

#1475 [City] Make event list scroller not jump.
  CHANGELOG.md
  src/lib/Scenes/City/Components/EventList.tsx
Labels: Jira Synced

#1473 Only ever show one city picker at a time
  CHANGELOG.md
  Example/Podfile.lock
  Pod/Classes/ViewControllers/ARMapContainerViewController.m
Labels: Jira Synced

#1476 Bmw art list section
  Example/Podfile.lock
  src/lib/Scenes/City/CityBMWList.tsx
  src/lib/Scenes/City/Components/AllEvents.tsx
Labels: Merge On Green

#1474 Switch to fork of react-native-mapbox-gl
  CHANGELOG.md
  Example/Podfile.lock
  package.json
  src/lib/Scenes/Map/GlobalMap.tsx
  yarn.lock
Labels: Merge On Green

#1481 Follow up on #1478
  src/__generated__/DetailTestsQuery.graphql.ts
  src/__generated__/DetailTestsQuery.queryMap.json
  src/__generated__/Detail_show.graphql.ts
  src/__generated__/QueryRenderersShowQuery.graphql.ts
  src/__generated__/QueryRenderersShowQuery.queryMap.json
  src/__generated__/ShowQuery.graphql.ts
  src/__generated__/ShowQuery.queryMap.json
  src/__generated__/ShowTestsQuery.graphql.ts
  src/__generated__/ShowTestsQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/lib/Components/HoursCollapsible.tsx
  src/lib/Scenes/Show/Screens/Detail.tsx
Labels: Merge On Green

#1483 LD-448 - Fixes BMW content not having image
  src/__generated__/GlobalMapTestsQuery.graphql.ts
  src/__generated__/GlobalMapTestsQuery.queryMap.json
  src/__generated__/GlobalMap_viewer.graphql.ts
  src/__generated__/MapRendererQuery.graphql.ts
  src/__generated__/MapRendererQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/lib/Scenes/City/Components/BMWEventSection/index.tsx
  src/lib/Scenes/Map/GlobalMap.tsx
Labels: Jira Synced

#1462 Error screen
  CHANGELOG.md
  Example/Podfile.lock
  src/lib/Scenes/City/City.tsx
  src/lib/Scenes/Map/Components/CitySwitcherButton.tsx
  src/lib/Scenes/Map/EventEmitter.ts
  src/lib/Scenes/Map/GlobalMap.tsx
  src/lib/Scenes/Map/MapRenderer.tsx
  src/lib/Scenes/Map/types.ts
Labels: Jira Synced, Merge On Green

#1484 Hide Artists title when there are zero artists
  src/__generated__/DetailTestsQuery.graphql.ts
  src/__generated__/DetailTestsQuery.queryMap.json
  src/__generated__/Detail_show.graphql.ts
  src/__generated__/FairBoothQuery.graphql.ts
  src/__generated__/FairBoothQuery.queryMap.json
  src/__generated__/FairBoothTestsQuery.graphql.ts
  src/__generated__/FairBoothTestsQuery.queryMap.json
  src/__generated__/QueryRenderersShowQuery.graphql.ts
  src/__generated__/QueryRenderersShowQuery.queryMap.json
  src/__generated__/ShowArtistsPreviewTestsQuery.graphql.ts
  src/__generated__/ShowArtistsPreviewTestsQuery.queryMap.json
  src/__generated__/ShowArtistsPreview_show.graphql.ts
  src/__generated__/ShowQuery.graphql.ts
  src/__generated__/ShowQuery.queryMap.json
  src/__generated__/ShowTestsQuery.graphql.ts
  src/__generated__/ShowTestsQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/lib/Components/Show/ShowArtistsPreview.tsx
  src/lib/Scenes/Show/Screens/Detail.tsx
  src/lib/Scenes/Show/__stories__/Show.story.tsx
Labels: Jira Synced

#1485 LD-416 - Fixes spinner on ShowItemRow
  CHANGELOG.md
  data/schema.graphql
  src/__generated__/CitySavedListQuery.graphql.ts
  src/__generated__/CitySavedListQuery.queryMap.json
  src/__generated__/CitySavedList_viewer.graphql.ts
  src/__generated__/QueryRenderersCitySavedListQuery.graphql.ts
  src/__generated__/QueryRenderersCitySavedListQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/lib/Components/Buttons/InvertedButton.tsx
  src/lib/Components/Lists/ShowItemRow.tsx
  src/lib/Scenes/City/CitySavedList.tsx
Labels: Jira Synced, Merge On Green

#1486 Update the changelog in the deploy script
  scripts/release.js
Labels: Merge On Green

#1487 Fixes drawer UX
  CHANGELOG.md
  Pod/Classes/ViewControllers/ARMapContainerViewController.m
Labels: Jira Synced

#1490 [GraphQL] Don't re-instate preheated cache after invalidation
  CHANGELOG.md
  Emission.podspec
  Example/Podfile.lock
  Example/Pods/Pods.xcodeproj/project.pbxproj
  Pod/Assets/PreHeatedGraphQLCache/PreheatedCacheCreatedAt.txt
  Pod/Classes/GraphQL/ARGraphQLQueryCache.h
  Pod/Classes/GraphQL/ARGraphQLQueryCache.m
  package.json
  scripts/preheatGraphQLCache.js
  scripts/release.js
Labels: Jira Synced

#1495 Tappable items in when pulley is semi-closed
  Pod/Classes/ViewControllers/ARMapContainerViewController.m
  dangerfile.ts
Labels: Merge On Green

#1500 Fixes missing "view all shows" link in sponsored content sections
  CHANGELOG.md
  src/lib/Scenes/City/Components/BMWEventSection/index.tsx
Labels: Jira Synced, Merge On Green

#1501 Google maps fix
  Example/Emission/Info.plist
  src/lib/Components/LocationMap/index.tsx
Labels: Jira Synced

#1502 [relay] Make sure Map/City/Show/Favorites views all use the same environment and store.
  CHANGELOG.md
  src/lib/Scenes/Favorites/Components/Artists/Relay/FavoriteArtists.tsx
  src/lib/Scenes/Favorites/Components/Artworks/Relay/FavoriteArtworks.tsx
  src/lib/Scenes/Favorites/Components/Categories/Relay/FavoriteCategories.tsx
  src/lib/Scenes/Favorites/Components/Fairs/Relay/FavoriteFairs.tsx
  src/lib/Scenes/Favorites/Components/Shows/Relay/FavoriteShows.tsx
  src/lib/relay/QueryRenderers.tsx
Labels: Jira Synced

#1506 Fixes crash on stub shows with no partner profile image
  CHANGELOG.md
  src/lib/Components/Lists/ShowItemRow.tsx
Labels: Merge On Green

#1513 Updates drawer sub-scrollview enabled state when tabs change 📱
  CHANGELOG.md
  Example/Podfile.lock
  Pod/Classes/ViewControllers/ARMapContainerViewController.m
  src/lib/Scenes/City/City.tsx
Labels: Merge On Green

#1514 Swap scrollable tab bar with fixed width version
  CHANGELOG.md
  Example/Podfile.lock
  src/lib/Components/TabBar.tsx
  src/lib/Scenes/City/City.tsx
  src/lib/Scenes/Home/Components/__tests__/__snapshots__/TabBar-tests.tsx.snap
  src/lib/Scenes/Home/index.tsx
Labels: Merge On Green

#1516 Fewer city render passes
  CHANGELOG.md
  src/lib/Scenes/City/City.tsx
  src/lib/Scenes/Map/GlobalMap.tsx
Labels: Merge On Green

#1521 Only includes Podspec metadata on releases #trivial
  Emission.podspec
  Example/Podfile.lock
  Example/Pods/Pods.xcodeproj/project.pbxproj
  scripts/release.js
Labels: Jira Synced

#1517 Updates copy in Shows tab on Favorites
  CHANGELOG.md
  src/lib/Scenes/Favorites/Components/Shows/index.tsx
Labels: Jira Synced

#1523 LD-470 - Fixes multiple instances of show opening on tap
  src/lib/Components/Lists/ShowItemRow.tsx
Labels: Jira Synced

#1522 LD-482 - Fair is_active
  CHANGELOG.md
  src/__generated__/FairDetailShowsQuery.graphql.ts
  src/__generated__/FairDetailShowsQuery.queryMap.json
  src/__generated__/FairDetailTestsQuery.graphql.ts
  src/__generated__/FairDetailTestsQuery.queryMap.json
  src/__generated__/FairDetail_fair.graphql.ts
  src/__generated__/FairQuery.graphql.ts
  src/__generated__/FairQuery.queryMap.json
  src/__generated__/FairTestsQuery.graphql.ts
  src/__generated__/FairTestsQuery.queryMap.json
  src/__generated__/QueryRenderersFairQuery.graphql.ts
  src/__generated__/QueryRenderersFairQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/lib/Scenes/Fair/Screens/FairDetail.tsx
Labels: Jira Synced

#1519 Adds a hitslop to the button component, and uses it in show list items
  CHANGELOG.md
  src/lib/Components/Buttons/InvertedButton.tsx
  src/lib/Components/Buttons/__tests__/__snapshots__/InvertedButton-tests.tsx.snap
  src/lib/Components/Home/ArtistRails/__tests__/__snapshots__/ArtistCard-tests.tsx.snap
  src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Message-tests.tsx.snap
  src/lib/Components/Lists/ShowItemRow.tsx
  src/lib/Scenes/Show/Components/ShowHeader/__tests__/__snapshots__/ShowHeader-tests.tsx.snap
Labels: Jira Synced, Merge On Green

#1527 narrows show detail column by 15 px to fit saved button in view
  src/lib/Components/Lists/ShowItemRow.tsx
Labels: Jira Synced

#1524 Fix UI issues in Saves and Follows on non iPhone X devices
  CHANGELOG.md
  src/lib/Components/ScrollableTabBar.tsx
  src/lib/Scenes/Favorites/index.tsx
Labels: Jira Synced

#1525 Copy update in BMW section title
  src/lib/Scenes/City/Components/AllEvents.tsx
  src/lib/Scenes/City/Components/BMWEventSection/index.tsx
Labels: Jira Synced

#1530 LD-483 - Adds museums to all shows
  src/lib/Scenes/City/cityTabs.ts
  src/lib/Scenes/Map/GlobalMap.tsx
Labels: Jira Synced, Merge On Green

#1529 Relay no longer caches GraphQL responses which contain errors field
  CHANGELOG.md
  src/lib/relay/middlewares/__tests__/cacheMiddleware-tests.ts
  src/lib/relay/middlewares/cacheMiddleware.ts
Labels: Jira Synced

#1531 LD-506 - Adds pressReleaseUrl to show moreInfo
  CHANGELOG.md
  data/schema.graphql
  src/__generated__/MoreInfoTestsQuery.graphql.ts
  src/__generated__/MoreInfoTestsQuery.queryMap.json
  src/__generated__/MoreInfo_show.graphql.ts
  src/__generated__/QueryRenderersShowMoreInfoQuery.graphql.ts
  src/__generated__/QueryRenderersShowMoreInfoQuery.queryMap.json
  src/__generated__/QueryRenderersShowQuery.graphql.ts
  src/__generated__/QueryRenderersShowQuery.queryMap.json
  src/__generated__/ShowQuery.graphql.ts
  src/__generated__/ShowQuery.queryMap.json
  src/__generated__/ShowTestsQuery.graphql.ts
  src/__generated__/ShowTestsQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/lib/Scenes/Show/Screens/MoreInfo.tsx
Labels: Jira Synced

#1533 Small update to chevron size
  src/lib/Components/Buttons/__tests__/__snapshots__/CaretButton-tests.tsx.snap
  src/lib/Icons/ChevronIcon.tsx
  src/lib/Scenes/Fair/Components/__tests__/__snapshots__/ArtistsExhibitorsWorksLink-tests.tsx.snap
  src/lib/Scenes/Fair/Screens/__tests__/__snapshots__/FairMoreInfo-tests.tsx.snap
Labels: Merge On Green

#1534 User location button hides when user is outside of currently selected city
  CHANGELOG.md
  Pod/Classes/ViewControllers/ARMapContainerViewController.m
  src/lib/Scenes/Map/GlobalMap.tsx
  src/lib/Scenes/Map/MapContainer.tsx
  src/lib/Scenes/Map/MapRenderer.tsx
  src/lib/Scenes/Map/__stories__/Map.story.tsx
Labels: Jira Synced

#1538 LD-490 - Updates dayThresholds for opening/closing
  CHANGELOG.md
  src/lib/Scenes/Map/GlobalMap.tsx
  src/lib/Scenes/Map/bucketCityResults.ts
  src/lib/relay/QueryRenderers.tsx
Labels: Jira Synced

#1537 Configure a maxZoom for map component
  src/lib/Scenes/Map/GlobalMap.tsx
Labels: Jira Synced

#1536 LD-510 - Adds correct formatting to time in show event section
  CHANGELOG.md
  src/__generated__/EventSectionTestsQuery.queryMap.json
  src/__generated__/MoreInfoTestsQuery.graphql.ts
  src/__generated__/MoreInfoTestsQuery.queryMap.json
  src/__generated__/MoreInfo_show.graphql.ts
  src/__generated__/QueryRenderersShowMoreInfoQuery.graphql.ts
  src/__generated__/QueryRenderersShowMoreInfoQuery.queryMap.json
  src/__generated__/QueryRenderersShowQuery.graphql.ts
  src/__generated__/QueryRenderersShowQuery.queryMap.json
  src/__generated__/ShowEventSectionTestsQuery.graphql.ts
  src/__generated__/ShowEventSectionTestsQuery.queryMap.json
  src/__generated__/ShowEventSection_event.graphql.ts
  src/__generated__/ShowQuery.graphql.ts
  src/__generated__/ShowQuery.queryMap.json
  src/__generated__/ShowTestsQuery.graphql.ts
  src/__generated__/ShowTestsQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/lib/Scenes/Show/Components/EventSection.tsx
  src/lib/Scenes/Show/Components/ShowEventSection.tsx
  src/lib/Scenes/Show/Components/__tests__/ShowEventSection-tests.tsx
  src/lib/Scenes/Show/Components/__tests__/__snapshots__/EventSection-tests.tsx.snap
  src/lib/Scenes/Show/Components/__tests__/__snapshots__/ShowEventSection-tests.tsx.snap
  src/lib/Scenes/Show/Screens/MoreInfo.tsx
Labels: Jira Synced

#1540 Date fix
  src/__generated__/GlobalMapTestsQuery.graphql.ts
  src/__generated__/GlobalMapTestsQuery.queryMap.json
  src/__generated__/GlobalMap_viewer.graphql.ts
  src/__generated__/MapRendererQuery.graphql.ts
  src/__generated__/MapRendererQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/lib/Scenes/Show/Components/ShowEventSection.tsx
Labels: Merge On Green

#1535 Fixes Misplaced Scrollbar on Saved/Follows shows
  src/lib/Scenes/Favorites/Components/Shows/index.tsx
Labels: Jira Synced, Merge On Green

#1532 Replaces start/end date range with "Ongoing" to Shows running for 2 or more years
  CHANGELOG.md
  src/__generated__/DetailTestsQuery.graphql.ts
  src/__generated__/DetailTestsQuery.queryMap.json
  src/__generated__/QueryRenderersShowQuery.graphql.ts
  src/__generated__/QueryRenderersShowQuery.queryMap.json
  src/__generated__/ShowHeader_show.graphql.ts
  src/__generated__/ShowItem_show.graphql.ts
  src/__generated__/ShowQuery.graphql.ts
  src/__generated__/ShowQuery.queryMap.json
  src/__generated__/ShowTestsQuery.graphql.ts
  src/__generated__/ShowTestsQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/lib/Components/Lists/ShowItemRow.tsx
  src/lib/Scenes/City/Components/Event/index.tsx
  src/lib/Scenes/Map/exhibitionPeriodParser.ts
  src/lib/Scenes/Show/Components/ShowHeader/ShowHeader.tsx
  src/lib/Scenes/Show/Components/Shows/Components/ShowItem.tsx
Labels: Jira Synced, Merge On Green

#1541 Reset zoom, pitch and heading upon city switch
  CHANGELOG.md
  src/lib/Scenes/Map/GlobalMap.tsx
Labels: Jira Synced

#1549 Removes openShow from tracking #trivial
  src/lib/Components/Lists/ShowItemRow.tsx
  src/lib/Scenes/City/Components/Event/index.tsx
  src/lib/utils/track.ts
Labels: Merge On Green

#1552 LD-521 - Adds opening reception header to stub shows #trivial
  src/lib/Scenes/Show/Screens/MoreInfo.tsx
Labels: Jira Synced, Merge On Green

#1326 Sets up making sure there's a phone number on a users's account when signing up for an auction
  CHANGELOG.md
  src/__generated__/ConfirmBidUpdateUserMutation.graphql.ts
  src/__generated__/ConfirmBidUpdateUserMutation.queryMap.json
  src/__generated__/RegistrationUpdateUserMutation.graphql.ts
  src/__generated__/RegistrationUpdateUserMutation.queryMap.json
  src/__generated__/complete.queryMap.json
  src/lib/Components/Bidding/Screens/BillingAddress.tsx
  src/lib/Components/Bidding/Screens/ConfirmBid.tsx
  src/lib/Components/Bidding/Screens/Registration.tsx
  src/lib/Components/Bidding/Screens/__tests__/BillingAddress-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/Registration-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/__snapshots__/BillingAddress-tests.tsx.snap
  src/lib/Components/Bidding/__stories__/BidFlow.story.tsx
  src/lib/Components/Bidding/__tests__/BidFlow-tests.tsx
  src/lib/Components/Bidding/types.d.ts
  src/lib/Scenes/Map/__tests__/GlobalMap-tests.tsx
Labels: Auctions, Merge On Green

#1554 Fixes scrollable tab bar on global saves & follows
  CHANGELOG.md
  src/lib/Components/ScrollableTabBar.tsx
Labels: Jira Synced, Merge On Green

#1555 Adds back Danger rule requiring tests for new files #trivial
  dangerfile.ts
Labels: Merge On Green

#1556 LD-531 - Adds correct margin/padding to last carousel image
  CHANGELOG.md
  src/lib/Scenes/Show/Components/ShowHeader/Components/Carousel.tsx
  src/lib/Scenes/Show/Components/ShowHeader/Components/__tests__/__snapshots__/Carousel-tests.tsx.snap
  storybook/storyLoader.js
Labels: Jira Synced, Merge On Green

#1557 LD-539 - Fixes doubled press release in show more info
  src/lib/Scenes/Show/Screens/MoreInfo.tsx
Labels: Jira Synced

#1558 Location is now a boolean in FairBoothPreviewHeader #trivial
  src/lib/Scenes/Fair/Components/FairBoothPreview/Components/FairBoothPreviewHeader.tsx
Labels: Merge On Green

#1563 Removes second sort on brick shows
  CHANGELOG.md
  src/lib/Scenes/City/Components/EventSection/index.tsx
Labels: Merge On Green

#1561 Fixes City not re-rendering after a MP request is successfully retried
  CHANGELOG.md
  src/lib/Scenes/Map/GlobalMap.tsx
Labels: Jira Synced

#1567 LD-552 - Fixes BMW save button
  CHANGELOG.md
  src/lib/Scenes/City/Components/AllEvents.tsx
Labels: Jira Synced
