Repository artsy/emission, pull requests merged in 2019-12, with the labels that each got.

#1983 Partner artworks to InfiniteScrollGrid
  data/complete.queryMap.json
  src/__generated__/PartnerArtworkInfiniteScrollGridQuery.graphql.ts
  src/__generated__/PartnerArtworkTestsQuery.graphql.ts
  src/__generated__/PartnerArtwork_partner.graphql.ts
  src/__generated__/PartnerQuery.graphql.ts
  src/__generated__/PartnerRefetchQuery.graphql.ts
  src/lib/Components/ArtworkGrids/InfiniteScrollArtworksGrid.tsx
  src/lib/Scenes/Partner/Components/PartnerArtwork.tsx
  src/lib/Scenes/Partner/Components/__fixtures__/PartnerArtwork-fixture.ts
  src/lib/Scenes/Partner/Components/__tests__/PartnerArtwork-tests.tsx
  src/lib/Scenes/Partner/Components/__tests__/__snapshots__/PartnerArtwork-tests.tsx.snap
Labels: Merge On Green, Version: Patch

#1981 [MX-114] Infrastructure for hiding back button on Partner view
  Example/Emission/AppDelegate.m
  Pod/Classes/Core/ARSwitchBoardModule.h
  Pod/Classes/Core/ARSwitchBoardModule.m
  src/lib/Components/StickyTabPage/StickyTabPage.tsx
  src/lib/Components/StickyTabPage/StickyTabScrollView.tsx
Labels: Version: Patch

#1985 Show sticky header based on scroll offset rather than velocity
  src/lib/Components/StickyTabPage/StickyTabScrollView.tsx
Labels: Merge On Green, Version: Patch

#1972 [ME-84] Add recent searches
  npm-podspecs.json
  package.json
  src/lib/Scenes/Search/AutosuggestResults.tsx
  src/lib/Scenes/Search/FadeIn.tsx
  src/lib/Scenes/Search/RecentSearches.tsx
  src/lib/Scenes/Search/Search.tsx
  src/lib/Scenes/Search/SearchResult.tsx
  src/lib/Scenes/Search/SearchResultList.tsx
  src/lib/Scenes/Search/__tests__/AutosuggestResults-tests.tsx
  src/lib/Scenes/Search/__tests__/RecentSearches-tests.tsx
  src/lib/Scenes/Search/__tests__/Search-tests.tsx
  src/setupJest.ts
  yarn.lock
Labels: Jira Synced, Merge On Green, Version: Patch

#1982 StickyTabs perf + UX improvements
  data/complete.queryMap.json
  src/__generated__/PartnerQuery.graphql.ts
  src/__generated__/PartnerRefetchQuery.graphql.ts
  src/__generated__/PartnerShowsInfiniteScrollGridQuery.graphql.ts
  src/__generated__/PartnerShowsTestsQuery.graphql.ts
  src/__generated__/PartnerShows_partner.graphql.ts
  src/lib/Components/Artist/ArtistAbout.tsx
  src/lib/Components/Artist/ArtistArtworks/index.tsx
  src/lib/Components/Artist/ArtistShows/index.tsx
  src/lib/Components/StickyTabPage/SnappyHorizontalRail.tsx
  src/lib/Components/StickyTabPage/StickyTabPage.tsx
  src/lib/Components/StickyTabPage/StickyTabPageFlatList.tsx
  src/lib/Components/StickyTabPage/StickyTabPageScrollView.tsx
  src/lib/Components/StickyTabPage/StickyTabPageTabBar.tsx
  src/lib/Components/StickyTabPage/StickyTabScrollView.tsx
  src/lib/Components/StickyTabPage/reanimatedHelpers.ts
  src/lib/Containers/__tests__/Artist-tests.tsx
  src/lib/Scenes/Partner/Components/PartnerArtwork.tsx
  src/lib/Scenes/Partner/Components/PartnerOverview.tsx
  src/lib/Scenes/Partner/Components/PartnerShows.tsx
  src/lib/Scenes/Partner/Components/PartnerShowsRail.tsx
  src/lib/Scenes/Partner/Components/__tests__/PartnerArtwork-tests.tsx
  src/lib/Scenes/Partner/Components/__tests__/PartnerOverview-tests.tsx
  src/lib/Scenes/Partner/Components/__tests__/PartnerShows-tests.tsx
  src/lib/Scenes/Partner/Components/__tests__/__snapshots__/PartnerArtwork-tests.tsx.snap
Labels: Merge On Green, Version: Patch

#1989 Adds note about auto-deploys
  README.md
Labels: Version: Patch

#1986 Updates to Node 12
  .nvmrc
  .travis.yml
  CHANGELOG.md
  package.json
  yarn.lock
Labels: Merge On Green, Version: Patch

#1991 MX-116 - Fixes markdown bug causing Artwork crash
  Example/Podfile.lock
  src/lib/utils/renderMarkdown.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#1992 Updates point people
  README.md
Labels: Version: Patch

#1993 Refactor and modernize Consignments/Welcome & Inbox empty state
  src/lib/Components/Consignments/Screens/Welcome.tsx
  src/lib/Components/Consignments/Screens/__tests__/__snapshots__/Welcome-tests.tsx.snap
  src/lib/Components/Consignments/__tests__/__snapshots__/index-tests.tsx.snap
  src/lib/Components/Inbox/Conversations/ZeroStateInbox.tsx
  src/lib/Components/Inbox/Conversations/index.tsx
  src/lib/Containers/Conversation.tsx
  src/lib/Containers/Inbox.tsx
  src/lib/Containers/__tests__/Inbox-tests.tsx
Labels: Merge On Green, Version: Patch

#1995 [MX-54] App Ratings Prompt
  .circleci/config.yml
  .ruby-version
  Emission.podspec
  Example/Emission.xcodeproj/project.pbxproj
  Example/Emission/AppDelegate.m
  Example/EmissionTests/Fixtures/ReferenceImages/EmissionTests-TestApps/OpaqueImageViewComponent_with_column_layout_maintains_the_aspect_ratio_when_automatically_sizing_to_fill_the_available_size_1@2x.png
  Example/EmissionTests/Fixtures/ReferenceImages/EmissionTests-TestApps/OpaqueImageViewComponent_with_column_layout_maintains_the_aspect_ration_when_given_an_explicit_width_1@2x.png
  Example/EmissionTests/Fixtures/ReferenceImages/EmissionTests-TestApps/OpaqueImageViewComponent_with_row_layout_maintains_the_aspect_ratio_when_automatically_sizing_to_fill_the_available_size_1@2x.png
  Example/EmissionTests/Fixtures/ReferenceImages/EmissionTests-TestApps/OpaqueImageViewComponent_with_row_layout_maintains_the_aspect_ration_when_given_an_explicit_height_1@2x.png
  Example/EmissionTests/Fixtures/ReferenceImages/EmissionTests-TestApps/OpaqueImageViewComponent_with_row_layout_maintains_the_aspect_ration_when_given_an_explicit_width_1@2x.png
  Example/EmissionTests/ReferenceImages/EmissionTests-TestApps/OpaqueImageViewComponent_with_column_layout_maintains_the_aspect_ration_when_given_an_explicit_width_1@3x.png
  Example/EmissionTests/ReferenceImages/EmissionTests-TestApps/OpaqueImageViewComponent_with_row_layout_maintains_the_aspect_ratio_when_automatically_sizing_to_fill_the_available_size_1@3x.png
  Example/EmissionTests/ReferenceImages/EmissionTests-TestApps/OpaqueImageViewComponent_with_row_layout_maintains_the_aspect_ration_when_given_an_explicit_height_1@3x.png
  Example/EmissionTests/ReferenceImages/EmissionTests-TestApps/OpaqueImageViewComponent_with_row_layout_maintains_the_aspect_ration_when_given_an_explicit_width_1@3x.png
  Example/EmissionTests/TestHelper.m
  Example/Podfile
  Example/Podfile.lock
  Pod/Classes/Core/AREmission.h
  Pod/Classes/Core/AREmission.m
  Pod/Classes/Core/AREventsModule.m
  package.json
  src/lib/Components/Artist/ArtistHeader.tsx
  src/lib/NativeModules/Events.tsx
  src/lib/Scenes/Artwork/Components/ArtworkActions.tsx
Labels: Jira Synced, Version: Patch

#1998 Run unit tests on master
  .circleci/config.yml
Labels: Version: Patch

#2003 Updates emission VC to expose artworkID
  Pod/Classes/ViewControllers/ARArtworkComponentViewController.h
  Pod/Classes/ViewControllers/ARArtworkComponentViewController.m
Labels: Merge On Green, Version: Patch

#2004 Points to our fork of tipsi-stripe #trivial
  Example/Podfile.lock
  package.json
  yarn.lock
Labels: Merge On Green, Version: Patch

#2002 Fix sticky tab header positioning when content is not so high
  src/lib/Components/StickyTabPage/StickyTabPageFlatList.tsx
Labels: Merge On Green, Version: Patch

#2008 Updates Danger rule for adding tests for new files
  dangerfile.ts
Labels: Version: Patch

#1999 Adding more tests for search UI
  data/complete.queryMap.json
  src/__generated__/AutosuggestResultsPaginationQuery.graphql.ts
  src/__generated__/AutosuggestResultsQuery.graphql.ts
  src/lib/Scenes/Artwork/__tests__/Artwork-tests.tsx
  src/lib/Scenes/Search/AutosuggestResults.tsx
  src/lib/Scenes/Search/__tests__/AutosuggestResults-tests.tsx
  src/lib/Scenes/Search/__tests__/RecentSearches-tests.tsx
  src/lib/Scenes/Search/__tests__/Search-tests.tsx
  src/lib/Scenes/Search/__tests__/SearchResult-tests.tsx
  src/lib/tests/extractText.ts
  src/setupJest.ts
Labels: Version: Patch

#2006 Moves collection screens to new a sub dir of collections
  src/lib/Scenes/Collection/Collection.tsx
  src/lib/Scenes/Collection/Screens/CollectionHeader.tsx
  src/lib/Scenes/Collection/Screens/__tests__/CollectionHeader-tests.tsx
  src/lib/Scenes/Collection/Screens/__tests__/__snapshots__/CollectionHeader-tests.tsx.snap
Labels: Version: Patch

#2009 MX-100 - Removes SearchLink from Fair
  src/lib/Scenes/Fair/Components/SearchLink.tsx
  src/lib/Scenes/Fair/Components/__tests__/SearchLink-tests.tsx
  src/lib/Scenes/Fair/Components/__tests__/__snapshots__/SearchLink-tests.tsx.snap
  src/lib/Scenes/Fair/Screens/FairDetail.tsx
Labels: Jira Synced, Version: Patch

#2010 Fix artist header when `bylineRequired` field is an empty string.
  src/lib/Components/Artist/ArtistHeader.tsx
Labels: Version: Patch

#2011 [MX-75] fix scroll to bottom in conversations
  src/lib/Components/Inbox/Conversations/Messages.tsx
Labels: Jira Synced, Version: Patch

#2013 Adds documentation for releasing iOS features
  .circleci/config.yml
  docs/adding_a_lab_option.md
  docs/developing_a_feature.md
Labels: Merge On Green, Version: Patch

#2014 Removes bundler installation from deploy job
  .circleci/config.yml
Labels: Merge On Green, Version: Patch

#2012 Include partner's name on copy stating bidders agree to Artsy's COS
  Example/Emission/ARRootViewController.m
  data/complete.queryMap.json
  src/__generated__/ArtworkExtraLinks_artwork.graphql.ts
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/ArtworkRefetchQuery.graphql.ts
  src/__generated__/ArtworkTestsQuery.graphql.ts
  src/__generated__/BidFlowSelectMaxBidRendererQuery.graphql.ts
  src/__generated__/ConfirmBid_sale_artwork.graphql.ts
  src/__generated__/QueryRenderersBidFlowQuery.graphql.ts
  src/__generated__/SelectMaxBidRefetchQuery.graphql.ts
  src/lib/Components/Bidding/Screens/ConfirmBid/index.tsx
  src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmBid-tests.tsx.snap
  src/lib/Scenes/Artwork/Components/ArtworkExtraLinks/__tests__/index-tests.tsx
  src/lib/Scenes/Artwork/Components/ArtworkExtraLinks/__tests__/partnerName-tests.tsx
  src/lib/Scenes/Artwork/Components/ArtworkExtraLinks/index.tsx
  src/lib/Scenes/Artwork/Components/ArtworkExtraLinks/partnerName.tsx
Labels: Jira Synced, Version: Minor

#2017 Correct the punctuation for e.g. Phillips
  src/lib/Scenes/Artwork/Components/ArtworkExtraLinks/__tests__/partnerName-tests.tsx
  src/lib/Scenes/Artwork/Components/ArtworkExtraLinks/partnerName.tsx
Labels: Merge On Green, Version: Patch

#2016 Updates shows to use coverImage
  data/complete.queryMap.json
  src/__generated__/DetailTestsQuery.graphql.ts
  src/__generated__/QueryRenderersShowQuery.graphql.ts
  src/__generated__/ShowHeader_show.graphql.ts
  src/__generated__/ShowQuery.graphql.ts
  src/__generated__/ShowTestsQuery.graphql.ts
  src/__generated__/indexTestsQuery.graphql.ts
  src/lib/Scenes/Show/Components/ShowHeader/ShowHeader.tsx
  src/lib/Scenes/Show/Components/ShowHeader/__tests__/__snapshots__/ShowHeader-tests.tsx.snap
  src/lib/Scenes/Show/__tests__/fixtures/ShowFixture.ts
  src/lib/__fixtures__/ShowFixture.ts
Labels: Version: Patch

#2005 [MX-131] - Reskin consignment flow
  Example/.ruby-version
  Example/Emission/ARRootViewController.m
  Example/Podfile.lock
  src/lib/Components/Buttons/__stories__/Buttons.story.tsx
  src/lib/Components/Consignments/Components/ArtworkConsignmentTodo.tsx
  src/lib/Components/Consignments/Components/BottomAlignedButton.tsx
  src/lib/Components/Consignments/Components/ConsignmentBG.tsx
  src/lib/Components/Consignments/Components/DoneButton.tsx
  src/lib/Components/Consignments/Components/FormElements.tsx
  src/lib/Components/Consignments/Components/ImageSelection.tsx
  src/lib/Components/Consignments/Components/SearchResults.tsx
  src/lib/Components/Consignments/Components/TextArea.tsx
  src/lib/Components/Consignments/Components/TextInput.tsx
  src/lib/Components/Consignments/Components/Toggle.tsx
  src/lib/Components/Consignments/Components/__tests__/ConsignmentBG-tests.tsx
  src/lib/Components/Consignments/Components/__tests__/__snapshots__/ArtworkConsignmentTodo-tests.tsx.snap
  src/lib/Components/Consignments/Components/__tests__/__snapshots__/BottomAlignedButton-tests.tsx.snap
  src/lib/Components/Consignments/Components/__tests__/__snapshots__/ConsignmentBG-tests.tsx.snap
  src/lib/Components/Consignments/Components/__tests__/__snapshots__/ImageSelection-tests.tsx.snap
  src/lib/Components/Consignments/Components/__tests__/__snapshots__/SearchResults-tests.tsx.snap
  src/lib/Components/Consignments/Components/__tests__/__snapshots__/TextArea-tests.tsx.snap
  src/lib/Components/Consignments/Components/__tests__/__snapshots__/TextInput-tests.tsx.snap
  src/lib/Components/Consignments/Components/__tests__/__snapshots__/Toggle-tests.tsx.snap
  src/lib/Components/Consignments/Screens/Confirmation.tsx
  src/lib/Components/Consignments/Screens/ConsignmentsArtist.tsx
  src/lib/Components/Consignments/Screens/Edition.tsx
  src/lib/Components/Consignments/Screens/Location.tsx
  src/lib/Components/Consignments/Screens/Metadata.tsx
  src/lib/Components/Consignments/Screens/Overview.tsx
  src/lib/Components/Consignments/Screens/Provenance.tsx
  src/lib/Components/Consignments/Screens/SelectFromPhotoLibrary.tsx
  src/lib/Components/Consignments/Screens/Welcome.tsx
  src/lib/Components/Consignments/Screens/__tests__/Confirmation-tests.tsx
  src/lib/Components/Consignments/Screens/__tests__/__snapshots__/Edition-tests.tsx.snap
  src/lib/Components/Consignments/Screens/__tests__/__snapshots__/Location-tests.tsx.snap
  src/lib/Components/Consignments/Screens/__tests__/__snapshots__/Metadata-tests.tsx.snap
  src/lib/Components/Consignments/Screens/__tests__/__snapshots__/Overview-tests.tsx.snap
  src/lib/Components/Consignments/Screens/__tests__/__snapshots__/Provenance-tests.tsx.snap
  src/lib/Components/Consignments/Screens/__tests__/__snapshots__/SelectFromPhotoLibrary-tests.tsx.snap
  src/lib/Components/Consignments/Screens/__tests__/__snapshots__/Welcome-tests.tsx.snap
  src/lib/Components/Consignments/__stories__/ImageSelection.story.tsx
  src/lib/Components/Consignments/__tests__/__snapshots__/index-tests.tsx.snap
  src/lib/Components/UtilityViews/RotatingView.tsx
  src/lib/Containers/Inquiry.tsx
  src/lib/Containers/__tests__/__snapshots__/Inquiry-tests.tsx.snap
  src/lib/Icons/Consignments/CamIcon.tsx
  src/lib/Icons/Consignments/MoneyIcon.tsx
  src/lib/Icons/Consignments/OfferIcon.tsx
  src/lib/Icons/Consignments/SellIcon.tsx
  src/lib/Icons/Consignments/index.tsx
  src/lib/utils/useScreenDimensions.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#2018 [MX-70] - Guard against S3 upload crash
  src/lib/Components/Consignments/Screens/Overview.tsx
  src/lib/Components/Consignments/Submission/geminiUploadToS3.ts
Labels: Version: Patch
