Repository artsy/emission, pull requests merged in 2019-06, with the labels that each got.

#1635 [Lib] Remove unneeded @codemods-js/cli package #trivial
  package.json
  yarn.lock
Labels: Merge On Green

#1631 PURCHASE-1063: Add about this artist section to Artwork page
  CHANGELOG.md
  data/complete.queryMap.json
  src/__generated__/AboutArtist_artwork.graphql.ts
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/Artwork_artwork.graphql.ts
  src/lib/Scenes/Artwork/Artwork.tsx
  src/lib/Scenes/Artwork/Components/AboutArtist.tsx
  src/lib/Scenes/Artwork/Components/__tests__/AboutArtist-tests.tsx
  src/lib/__fixtures__/ArtworkFixture.ts
Labels: Jira Synced, Merge On Green

#1628 PURCHASE-1054: Artwork details widget
  Example/Pods/Pods.xcodeproj/project.pbxproj
  data/complete.queryMap.json
  src/__generated__/ArtworkDetails_artwork.graphql.ts
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/Artwork_artwork.graphql.ts
  src/lib/Scenes/Artwork/Artwork.tsx
  src/lib/Scenes/Artwork/Components/ArtworkDetails.tsx
  src/lib/Scenes/Artwork/Components/__stories__/ArtworkDetails.story.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ArtworkDetails-tests.tsx
  storybook/storyLoader.js
Labels: Jira Synced

#1657 Replace __id parameters with id #trivial
  data/complete.queryMap.json
  data/schema.graphql
  src/__generated__/ArtistForSaleArtworksGridQuery.graphql.ts
  src/__generated__/ArtistNotForSaleArtworksGridQuery.graphql.ts
  src/__generated__/ArtworkRailRefetchQuery.graphql.ts
  src/__generated__/ArtworksGridPaginationContainerQuery.graphql.ts
  src/__generated__/GeneArtworksGridQuery.graphql.ts
  src/__generated__/SaleArtworksGridQuery.graphql.ts
  src/lib/Components/ArtworkGrids/RelayConnections/ArtistForSaleArtworksGrid.tsx
  src/lib/Components/ArtworkGrids/RelayConnections/ArtistNotForSaleArtworksGrid.tsx
  src/lib/Components/ArtworkGrids/RelayConnections/GeneArtworksGrid.tsx
  src/lib/Components/ArtworkGrids/RelayConnections/SaleArtworksGrid.tsx
  src/lib/Components/FilteredInfiniteScrollGrid/ArtworksGridPaginationContainer.tsx
  src/lib/Components/Home/ArtworkRails/ArtworkRail.tsx
  src/lib/Scenes/Artwork/Components/__stories__/ArtworkAvailability.story.tsx
Labels: Merge On Green

#1678 [Artwork] Checks for layer before calling it
  src/lib/Scenes/Artwork/Artwork.tsx
Labels: Merge On Green

#1676 Artwork history
  CHANGELOG.md
  data/complete.queryMap.json
  src/__generated__/ArtworkHistory_artwork.graphql.ts
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/Artwork_artwork.graphql.ts
  src/lib/Scenes/Artwork/Artwork.tsx
  src/lib/Scenes/Artwork/Components/ArtworkHistory.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ArtworkHistory-tests.tsx
  src/lib/__fixtures__/ArtworkFixture.ts
Labels: Merge On Green

#1689 Artwork button updates and removes anchor wrapping ArtworkListItem
  Example/Pods/Pods.xcodeproj/project.pbxproj
  data/complete.queryMap.json
  src/__generated__/ArtistListItemTestsQuery.graphql.ts
  src/__generated__/ArtistListItem_artist.graphql.ts
  src/__generated__/ArtistsGroupedByNameTestsQuery.graphql.ts
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/DetailTestsQuery.graphql.ts
  src/__generated__/FairArtistsQuery.graphql.ts
  src/__generated__/FairArtistsRendererQuery.graphql.ts
  src/__generated__/FairArtistsTestsQuery.graphql.ts
  src/__generated__/FairBoothQuery.graphql.ts
  src/__generated__/FairBoothTestsQuery.graphql.ts
  src/__generated__/QueryRenderersShowQuery.graphql.ts
  src/__generated__/ShowArtistsPreviewTestsQuery.graphql.ts
  src/__generated__/ShowArtistsQuery.graphql.ts
  src/__generated__/ShowArtistsTestsQuery.graphql.ts
  src/__generated__/ShowQuery.graphql.ts
  src/__generated__/ShowTestsQuery.graphql.ts
  src/__generated__/indexTestsQuery.graphql.ts
  src/lib/Components/ArtistListItem.tsx
  src/lib/Components/ArtistsGroupedByName.tsx
  src/lib/Components/Show/ShowArtistsPreview.tsx
  src/lib/Components/Show/__tests__/ShowArtistsPreview-tests.tsx
  src/lib/Components/__tests__/ArtistListItem-tests.tsx
  src/lib/Components/__tests__/ArtistsGroupedByName-tests.tsx
  src/lib/Components/__tests__/__snapshots__/ArtistListItem-tests.tsx.snap
  src/lib/Components/__tests__/__snapshots__/ArtistsGroupedByName-tests.tsx.snap
  src/lib/Scenes/Artwork/Components/AboutArtist.tsx
  src/lib/Scenes/Artwork/Components/PartnerCard.tsx
  src/lib/Scenes/Artwork/Components/__tests__/PartnerCard-tests.tsx
  src/lib/Scenes/Fair/Screens/FairArtists.tsx
  src/lib/Scenes/Fair/Screens/__tests__/__snapshots__/FairArtists-tests.tsx.snap
  src/lib/Scenes/Show/Screens/ShowArtists.tsx
  src/lib/Scenes/Show/Screens/__tests__/__snapshots__/ShowArtists-tests.tsx.snap
  src/lib/__fixtures__/ShowFixture.ts
Labels: Version: Trivial
