Repository artsy/emission, pull requests merged in 2019-10, with the labels that each got.

#1895 PURCHASE-1541 - Fixes extralinks
  src/lib/Scenes/Artwork/Components/ArtworkExtraLinks.tsx
Labels: Jira Synced

#1896 PURCHASE-1536 - Fixes sale message for closed auctions
  Example/Podfile.lock
  src/lib/Scenes/Artwork/Components/CommercialInformation.tsx
  src/lib/Scenes/Artwork/Components/__tests__/CommercialInformation-tests.tsx
Labels: Jira Synced

#1899 PURCHASE-1544 & PURCHASE-1538: Handle artwork view for a non-auction sale and make sure links show
  data/complete.queryMap.json
  src/__generated__/ArtworkExtraLinks_artwork.graphql.ts
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/ArtworkRefetchQuery.graphql.ts
  src/__generated__/Artwork_artwork.graphql.ts
  src/lib/Scenes/Artwork/Artwork.tsx
  src/lib/Scenes/Artwork/Components/ArtworkExtraLinks.tsx
  src/lib/Scenes/Artwork/Components/CommercialInformation.tsx
  src/lib/Scenes/Artwork/Components/ContextCard.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ArtworkExtraLinks-tests.tsx
  src/lib/Scenes/Artwork/Components/__tests__/CommercialInformation-tests.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ContextCard-tests.tsx
  src/lib/Scenes/Artwork/__tests__/Artwork-tests.tsx
  src/lib/__fixtures__/ArtworkFixture.ts
Labels: Jira Synced

#1900 Remove mobx
  CHANGELOG.md
  package.json
  src/lib/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageCarouselCloseButton.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageCarouselFullScreen.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/FullScreen/ImageZoomView.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/FullScreen/IndexIndicator.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/FullScreen/StatusBarOverlay.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/FullScreen/VerticalSwipeToDismiss.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/FullScreen/useSpringFade.ts
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarouselContext.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarouselEmbedded.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/__tests__/ImageCarousel-tests.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/__tests__/ImageCarouselContext-tests.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/__tests__/useGlobalState-tests.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/useGlobalState.ts
  yarn.lock
Labels: Merge On Green

#1901 PURCHASE-1547 - Adds safety to image.url
  src/lib/Components/Artist/Articles/Article.tsx
  src/lib/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/lib/Components/Bidding/Screens/ConfirmBid/index.tsx
  src/lib/Components/Inbox/ActiveBids/ActiveBid.tsx
  src/lib/Components/Inbox/Conversations/ConversationSnippet.tsx
  src/lib/Components/Inbox/Conversations/Preview/ArtworkPreview.tsx
  src/lib/Components/Lists/SavedFairItemRow.tsx
  src/lib/tests/__tests__/MockRelayRendererFixtures.tsx
Labels: Jira Synced

#1906 PURCHASE-1543 - Artwork Auction refresh on state change
  CHANGELOG.md
  Example/Podfile.lock
  data/complete.queryMap.json
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/ArtworkRefetchQuery.graphql.ts
  src/__generated__/CommercialInformation_artwork.graphql.ts
  src/lib/Scenes/Artwork/Components/ArtworkExtraLinks.tsx
  src/lib/Scenes/Artwork/Components/AuctionCountDownTimer.tsx
  src/lib/Scenes/Artwork/Components/AuctionPrice.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/BidButton.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/BidButton-tests.tsx
  src/lib/Scenes/Artwork/Components/CommercialInformation.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ArtworkExtraLinks-tests.tsx
  src/lib/Scenes/Artwork/Components/__tests__/AuctionCountDownTimer-tests.tsx
  src/lib/Scenes/Artwork/Components/__tests__/AuctionPrice-tests.tsx
  src/lib/Scenes/Artwork/Components/__tests__/CommercialInformation-tests.tsx
Labels: Jira Synced

#1897 PURCHASE-1540 - Uses em dash between text in ReadMore
  CHANGELOG.md
  src/lib/Components/ReadMore.tsx
  src/lib/Components/__tests__/ReadMore-tests.tsx
Labels: Jira Synced

#1910 ME-17 Send RetryErrorBoundary errors to sentry
  src/lib/Components/RetryErrorBoundary.tsx
  src/setupJest.ts
Labels: Jira Synced, Merge On Green

#1911 ME-39 - Adds spinner to home page tabs when loading more
  src/lib/Containers/WorksForYou.tsx
  src/lib/Containers/__tests__/__snapshots__/WorksForYou-tests.tsx.snap
Labels: Jira Synced, Merge On Green

#1915 ME-51 - Load ForYouTab on launch
  src/lib/Scenes/Home/index.tsx
Labels: Jira Synced

#1912 PURCHASE-1584: Update AuctionCountDownTimer to handle liveStartAt
  CHANGELOG.md
  data/complete.queryMap.json
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/ArtworkRefetchQuery.graphql.ts
  src/__generated__/AuctionCountDownTimer_artwork.graphql.ts
  src/lib/Scenes/Artwork/Components/AuctionCountDownTimer.tsx
  src/lib/Scenes/Artwork/Components/CommercialInformation.tsx
  src/lib/Scenes/Artwork/Components/__tests__/AuctionCountDownTimer-tests.tsx
  src/lib/Scenes/Artwork/Components/__tests__/CommercialInformation-tests.tsx
  src/lib/tests/mockTimezone.tsx
  src/lib/utils/__tests__/formatDates-tests.tsx
  src/lib/utils/formatDates.tsx
Labels: Jira Synced

#1916 ME-21 - Moving chevron
  src/lib/Scenes/Artwork/Components/OtherWorks/ContextGridCTA.tsx
Labels: Jira Synced

#1917 ME-32 - Fixes Composer text input clip
  src/lib/Components/Inbox/Conversations/Composer.tsx
Labels: Jira Synced

#1914 ME-18 Send graphql request metrics to datadog
  CHANGELOG.md
  Example/Emission/AppDelegate.m
  Example/Emission/AppSetup.h
  Example/EmissionTests/TestHelper.m
  Pod/Classes/Core/AREmission.h
  Pod/Classes/Core/AREmission.m
  package.json
  src/lib/relay/createEnvironment.ts
  src/lib/relay/middlewares/timingMiddleware.ts
  src/lib/utils/__tests__/volleyClient-tests.ts
  src/lib/utils/volleyClient.ts
  src/setupJest.ts
Labels: Jira Synced, Merge On Green

#1923 No 'Contact Gallery' Button for artwork in closed auction
  CHANGELOG.md
  src/lib/Scenes/Artwork/Components/CommercialInformation.tsx
  src/lib/Scenes/Artwork/Components/__tests__/CommercialInformation-tests.tsx
Labels: Jira Synced

#1921 Fixes a few issues on the artwork view while auction is open for live bidding
  CHANGELOG.md
  src/lib/Scenes/Artwork/Components/AuctionCountDownTimer.tsx
  src/lib/Scenes/Artwork/Components/CommercialInformation.tsx
  src/lib/Scenes/Artwork/Components/__tests__/AuctionCountDownTimer-tests.tsx
  src/lib/Scenes/Artwork/__tests__/Artwork-tests.tsx
  src/lib/__fixtures__/ArtworkBidAction.ts
Labels: Jira Synced, Merge On Green

#1920 ME-62 - Center DarkNavigationButton content
  CHANGELOG.md
  src/lib/Components/Buttons/DarkNavigationButton.tsx
  src/lib/Components/Buttons/__stories__/Buttons.story.tsx
  src/lib/Components/Buttons/__tests__/__snapshots__/DarkNavigationButton-tests.tsx.snap
  src/lib/Scenes/Favorites/index.tsx
  src/lib/Scenes/Home/index.tsx
Labels: Jira Synced

#1924 Switch to use formattedStartDateTime for meta all the time
  CHANGELOG.md
  src/lib/Scenes/Artwork/Components/ContextCard.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ContextCard-tests.tsx
Labels: Jira Synced

#1926 User is able to see buyer's premium cost on iOS
  CHANGELOG.md
  Example/Emission/ARLabOptions.m
  data/complete.queryMap.json
  data/schema.graphql
  package.json
  src/__generated__/BidFlowSelectMaxBidRendererQuery.graphql.ts
  src/__generated__/ConfirmBid_sale_artwork.graphql.ts
  src/__generated__/PriceSummaryQuery.graphql.ts
  src/__generated__/PriceSummary_calculatedCost.graphql.ts
  src/__generated__/QueryRenderersBidFlowQuery.graphql.ts
  src/__generated__/SelectMaxBidRefetchQuery.graphql.ts
  src/lib/Components/Bidding/Components/PaymentInfo.tsx
  src/lib/Components/Bidding/Components/__tests__/__snapshots__/PaymentInfo-tests.tsx.snap
  src/lib/Components/Bidding/Screens/ConfirmBid/PriceSummary.tsx
  src/lib/Components/Bidding/Screens/ConfirmBid/index.tsx
  src/lib/Components/Bidding/Screens/CreditCardForm.tsx
  src/lib/Components/Bidding/Screens/Registration.tsx
  src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/SelectMaxBid-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmBid-tests.tsx.snap
  src/lib/Components/Bidding/Screens/__tests__/__snapshots__/CreditCardForm-tests.tsx.snap
  src/lib/Components/Bidding/Screens/__tests__/__snapshots__/Registration-tests.tsx.snap
  src/lib/Components/Bidding/__tests__/BidFlow-tests.tsx
  src/lib/Containers/__tests__/__snapshots__/RegistrationFlow-tests.tsx.snap
  yarn.lock
Labels: Jira Synced

#1939 Add artsy open source footer
  README.md
Labels: Merge On Green, Version: Patch

#1940 ME-58 fix saved artworks zero state
  src/lib/Components/States/ZeroState.tsx
  src/lib/Components/States/__stories__/ZeroState.story.tsx
  src/lib/Components/States/__tests__/ZeroState-tests.tsx
  src/lib/Containers/WorksForYou.tsx
  src/lib/Containers/__tests__/__snapshots__/WorksForYou-tests.tsx.snap
  src/lib/Scenes/Favorites/Components/Artists/index.tsx
  src/lib/Scenes/Favorites/Components/Artworks/index.tsx
  src/lib/Scenes/Favorites/Components/Categories/index.tsx
  src/lib/Scenes/Favorites/Components/Fairs/index.tsx
  src/lib/Scenes/Favorites/Components/Shows/index.tsx
Labels: Jira Synced, Version: Patch

#1936 Rename enablePriceTransparency to AROptionsPriceTransparency for consistency
  Example/Emission/ARLabOptions.m
  src/lib/Components/Bidding/Screens/ConfirmBid/index.tsx
  src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
Labels: Version: Patch

#1934 PURCHASE-1599: Consolidates Auction State across Artwork and Bid pages
  Example/Emission/ARRootViewController.m
  Example/Podfile.lock
  data/complete.queryMap.json
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/ArtworkRefetchQuery.graphql.ts
  src/__generated__/Artwork_artwork.graphql.ts
  src/__generated__/AuctionCountDownTimer_artwork.graphql.ts
  src/__generated__/CommercialInformation_artwork.graphql.ts
  src/lib/Components/Bidding/Components/Timer.tsx
  src/lib/Components/Bidding/Components/__tests__/Timer-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmBid-tests.tsx.snap
  src/lib/Components/Bidding/Screens/__tests__/__snapshots__/Registration-tests.tsx.snap
  src/lib/Components/Countdown/DurationProvider.tsx
  src/lib/Components/Countdown/StateManager.tsx
  src/lib/Components/Countdown/__tests__/Ticker-tests.tsx
  src/lib/Containers/__tests__/__snapshots__/RegistrationFlow-tests.tsx.snap
  src/lib/Scenes/Artwork/Artwork.tsx
  src/lib/Scenes/Artwork/Components/ArtworkExtraLinks.tsx
  src/lib/Scenes/Artwork/Components/AuctionCountDownTimer.tsx
  src/lib/Scenes/Artwork/Components/AuctionPrice.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/BidButton.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/BidButton-tests.tsx
  src/lib/Scenes/Artwork/Components/CommercialInformation.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ArtworkExtraLinks-tests.tsx
  src/lib/Scenes/Artwork/Components/__tests__/AuctionCountDownTimer-tests.tsx
  src/lib/Scenes/Artwork/Components/__tests__/AuctionPrice-tests.tsx
  src/lib/Scenes/Artwork/Components/__tests__/CommercialInformation-tests.tsx
  src/lib/Scenes/Artwork/__tests__/Artwork-tests.tsx
  src/lib/Scenes/Fair/Components/FairHeader/CountdownTimer.tsx
Labels: Version: Patch

#1941 Minor typo in docs: `stores` -> `stories`
  docs/adding_new_components.md
Labels: Version: Trivial

#1943 ME-42 Make sure artists feed is up-to-date on refresh
  src/lib/Containers/WorksForYou.tsx
Labels: Jira Synced, Version: Patch

#1946 Prevent concurrent builds on master
  package.json
  scripts/await-previous-builds.js
  scripts/release.js
  yarn.lock
Labels: Version: Patch

#1944 [PURCHASE-1545] All artwork details subfields have a ReadMore link
  src/lib/Components/ReadMore.tsx
  src/lib/Scenes/Artwork/Components/ArtworkDetails.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ArtworkDetails-tests.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#1949 [ME-77] Marks artworks as recently viewed
  Example/Podfile.lock
  __mocks__/react-relay.js
  data/complete.queryMap.json
  src/__generated__/ArtworkMarkAsRecentlyViewedQuery.graphql.ts
  src/lib/Scenes/Artwork/Artwork.tsx
  src/lib/Scenes/Artwork/__tests__/Artwork-tests.tsx
Labels: Version: Patch
