Repository artsy/emission, pull requests merged in 2019-07, with the labels that each got.

#1697 Use native image view in Carousel
  CHANGELOG.md
  Example/Podfile.lock
  data/complete.queryMap.json
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/ImageCarouselTestsQuery.graphql.ts
  src/__generated__/ImageCarousel_images.graphql.ts
  src/lib/Scenes/Artwork/Artwork.tsx
  src/lib/Scenes/Artwork/Components/ArtworkHeader.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageWithLoadingState.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/__tests__/ImageCarousel-tests.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/__tests__/ImageWithLoadingState-tests.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/__tests__/geometry-tests.ts
  src/lib/Scenes/Artwork/Components/ImageCarousel/geometry.ts
  src/lib/Scenes/Artwork/Components/OtherWorks/Header.tsx
Labels: Merge On Green

#1698 View In Room, Episode 2
  CHANGELOG.md
  data/complete.queryMap.json
  src/__generated__/ArtworkActionsTestsErrorQuery.graphql.ts
  src/__generated__/ArtworkActionsTestsQuery.graphql.ts
  src/__generated__/ArtworkActions_artwork.graphql.ts
  src/__generated__/ArtworkQuery.graphql.ts
  src/lib/Scenes/Artwork/Components/ArtworkActions.tsx
  src/lib/Scenes/Artwork/Components/__stories__/ArtworkActions.story.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ArtworkActions-tests.tsx
Labels: Merge On Green

#1695 PURCHASE-1229, PURCHASE-1236, PURCHASE-1231, PURCHASE-1225: iOS Artwork Page small changes and bug fixes
  data/complete.queryMap.json
  src/__generated__/ArtworkDetails_artwork.graphql.ts
  src/__generated__/ArtworkQuery.graphql.ts
  src/lib/Scenes/Artwork/Components/ArtworkDetails.tsx
  src/lib/Scenes/Artwork/Components/ArtworkTombstone.tsx
  src/lib/Scenes/Artwork/Components/__stories__/ArtworkDetails.story.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ArtworkDetails-tests.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ArtworkTombstone-tests.tsx
Labels: Jira Synced

#1699 Changes method parameter names to make the units for width+height in inches
  CHANGELOG.md
  Example/Emission/AppDelegate.m
  Example/Podfile.lock
  Example/Pods/Pods.xcodeproj/project.pbxproj
  Pod/Classes/TemporaryAPI/ARTemporaryAPIModule.h
  Pod/Classes/TemporaryAPI/ARTemporaryAPIModule.m
  package.json
Labels: Merge On Green

#1696 Refactored ArtistListItem to use palette EntityHeader component and added padding to artist cards
  src/lib/Components/ArtistListItem.tsx
  src/lib/Components/__tests__/__snapshots__/ArtistListItem-tests.tsx.snap
  src/lib/Components/__tests__/__snapshots__/ArtistsGroupedByName-tests.tsx.snap
  src/lib/Scenes/Artwork/Artwork.tsx
  src/lib/Scenes/Artwork/Components/AboutArtist.tsx
  src/lib/Scenes/Fair/Screens/__tests__/__snapshots__/FairArtists-tests.tsx.snap
  src/lib/Scenes/Show/Screens/__tests__/__snapshots__/ShowArtists-tests.tsx.snap
Labels: Jira Synced

#1701 PURCHASE-1228, PURCHASE-1239, PURCHASE-1234, PURCHASE-1240, PURCHASE-1241: Fix spacing in ArtworkHistory component and make OtherWorks to spec
  data/complete.queryMap.json
  src/__generated__/ArtistArtworkGrid_artwork.graphql.ts
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/Artwork_artwork.graphql.ts
  src/__generated__/PartnerArtworkGrid_artwork.graphql.ts
  src/__generated__/RelatedArtworkGrid_artwork.graphql.ts
  src/lib/Scenes/Artwork/Artwork.tsx
  src/lib/Scenes/Artwork/Components/ArtworkDetails.tsx
  src/lib/Scenes/Artwork/Components/ArtworkHistory.tsx
  src/lib/Scenes/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkContextArtist.tsx
  src/lib/Scenes/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/ArtistArtworkGrid.tsx
  src/lib/Scenes/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/PartnerArtworkGrid.tsx
  src/lib/Scenes/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/RelatedArtworkGrid.tsx
  src/lib/Scenes/Artwork/Components/OtherWorks/Header.tsx
  src/lib/Scenes/Artwork/Components/__stories__/ArtworkHistory.story.tsx
  storybook/storyLoader.js
Labels: Jira Synced

#1704 Styling improvements
  Example/Emission/ARRootViewController.m
  data/complete.queryMap.json
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/Artwork_artwork.graphql.ts
  src/lib/Components/ReadMore.tsx
  src/lib/Scenes/Artwork/Artwork.tsx
  src/lib/Scenes/Artwork/Components/ArtworkExtraLinks.tsx
  src/lib/Scenes/Artwork/Components/ArtworkHeader.tsx
  src/lib/Scenes/Artwork/Components/ArtworkTombstone.tsx
  src/lib/Scenes/Artwork/Components/CommercialInformation.tsx
  src/lib/Scenes/Artwork/Components/FollowArtistButton.tsx
  src/lib/Scenes/Artwork/Components/PartnerCard.tsx
  src/lib/__fixtures__/ArtworkFixture.ts
Labels: Jira Synced

#1700 PURCHASE-1249 Inject safe area insets into artwork page
  CHANGELOG.md
  Example/Emission/ARTopMenuViewController.m
  Pod/Classes/ViewControllers/ARArtworkComponentViewController.m
  Pod/Classes/ViewControllers/ARComponentViewController.h
  Pod/Classes/ViewControllers/ARComponentViewController.m
  Pod/Classes/ViewControllers/ARMapComponentViewController.m
  Pod/Classes/ViewControllers/ARMapContainerViewController.m
  package.json
  src/lib/AppRegistry.tsx
  src/lib/Scenes/Artwork/Artwork.tsx
  src/lib/Scenes/Artwork/__stories__/Artwork.story.tsx
  src/lib/Scenes/Artwork/__tests__/Artwork-tests.tsx
  src/lib/Scenes/Map/GlobalMap.tsx
  src/lib/Scenes/Map/MapContainer.tsx
  src/lib/Scenes/Map/MapRenderer.tsx
  src/lib/Scenes/Map/types.ts
  src/lib/types/SafeAreaInsets.ts
  yarn.lock
Labels: Merge On Green

#1715 Palette update @4.14.28
  Example/Pods/Pods.xcodeproj/project.pbxproj
  package.json
  src/lib/Components/__tests__/__snapshots__/ArtistListItem-tests.tsx.snap
  src/lib/Components/__tests__/__snapshots__/ArtistsGroupedByName-tests.tsx.snap
  src/lib/Scenes/Artwork/Components/__tests__/PartnerCard-tests.tsx
  src/lib/Scenes/ArtworkAttributionClassFAQ/__tests__/ArtworkAttributionClassFAQ-tests.tsx
  src/lib/Scenes/Fair/Screens/__tests__/__snapshots__/FairArtists-tests.tsx.snap
  src/lib/Scenes/Show/Screens/__tests__/__snapshots__/ShowArtists-tests.tsx.snap
  yarn.lock
Labels: Merge On Green

#1693 PURCHASE-1211 - Removes InvertedButton
  CHANGELOG.md
  Example/Emission/ARRootViewController.m
  src/lib/Components/Artist/Header.tsx
  src/lib/Components/Buttons/FlatWhite.tsx
  src/lib/Components/Buttons/InvertedButton.tsx
  src/lib/Components/Buttons/__stories__/Buttons.story.tsx
  src/lib/Components/Buttons/__tests__/InvertedButton-tests.tsx
  src/lib/Components/Buttons/__tests__/__snapshots__/InvertedButton-tests.tsx.snap
  src/lib/Components/Buttons/index.tsx
  src/lib/Components/Consignments/Components/CloseButton.tsx
  src/lib/Components/Consignments/Components/FormElements.tsx
  src/lib/Components/Consignments/Screens/Confirmation.tsx
  src/lib/Components/Consignments/Screens/Overview.tsx
  src/lib/Components/Consignments/Screens/Welcome.tsx
  src/lib/Components/Consignments/Screens/__tests__/__snapshots__/Overview-tests.tsx.snap
  src/lib/Components/Consignments/Screens/__tests__/__snapshots__/Welcome-tests.tsx.snap
  src/lib/Components/Gene/Header.tsx
  src/lib/Components/Home/ArtistRails/ArtistCard.tsx
  src/lib/Components/Home/ArtistRails/ArtistRail.tsx
  src/lib/Components/Home/ArtistRails/__tests__/__snapshots__/ArtistCard-tests.tsx.snap
  src/lib/Components/Home/ArtworkRails/ArtworkRailHeader.tsx
  src/lib/Components/Inbox/Conversations/Preview/InvoicePreview.tsx
  src/lib/Components/Inbox/Conversations/Preview/__tests__/__snapshots__/InvoicePreview-tests.tsx.snap
  src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Message-tests.tsx.snap
  src/lib/Components/Lists/ShowItemRow.tsx
  src/lib/Scenes/City/City.tsx
  src/lib/Scenes/City/Components/Event/index.tsx
  src/lib/Scenes/Fair/Components/FairBoothHeader.tsx
  src/lib/Scenes/Fair/Components/FairBoothPreview/Components/FairBoothPreviewHeader.tsx
  src/lib/Scenes/Fair/Components/FairBoothPreview/Components/__tests__/__snapshots__/FairBoothPreviewHeader-tests.tsx.snap
  src/lib/Scenes/Fair/Screens/__tests__/__snapshots__/FairDetail-tests.tsx.snap
  src/lib/Scenes/Home/Components/ForYou/Components/ArtworkCarouselHeader.tsx
  src/lib/Scenes/Show/Components/ShowHeader/ShowHeader.tsx
  src/lib/Scenes/Show/Components/ShowHeader/__tests__/__snapshots__/ShowHeader-tests.tsx.snap
Labels: Jira Synced, Merge On Green

#1685 PURCHASE-1178 - Adds context card
  CHANGELOG.md
  Example/Emission/ARRootViewController.m
  data/complete.queryMap.json
  data/schema.graphql
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/Artwork_artwork.graphql.ts
  src/__generated__/ContextCardFollowMutation.graphql.ts
  src/__generated__/ContextCard_artwork.graphql.ts
  src/lib/Components/ArtistListItem.tsx
  src/lib/Components/__tests__/__snapshots__/ArtistListItem-tests.tsx.snap
  src/lib/Components/__tests__/__snapshots__/ArtistsGroupedByName-tests.tsx.snap
  src/lib/Scenes/Artwork/Artwork.tsx
  src/lib/Scenes/Artwork/Components/ContextCard.tsx
  src/lib/Scenes/Artwork/Components/PartnerCard.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ContextCard-tests.tsx
  src/lib/Scenes/Artwork/Components/__tests__/PartnerCard-tests.tsx
  src/lib/Scenes/Fair/Screens/__tests__/__snapshots__/FairArtists-tests.tsx.snap
  src/lib/Scenes/Show/Screens/__tests__/__snapshots__/ShowArtists-tests.tsx.snap
  src/lib/__fixtures__/ArtworkFixture.ts
Labels: Jira Synced

#1717 [iOS Bug Bash] - PURCHASE-1000 - Button clip
  CHANGELOG.md
  src/lib/Components/Consignments/Components/BottomAlignedButton.tsx
  src/lib/Components/Consignments/Components/DoneButton.tsx
  src/lib/Components/Consignments/Screens/SelectFromPhotoLibrary.tsx
  src/lib/Components/Consignments/__stories__/BottomAligned.story.tsx
  src/lib/Containers/Inquiry.tsx
  src/lib/Containers/__tests__/__snapshots__/Inquiry-tests.tsx.snap
Labels: Jira Synced

#1720 [GROW-1392] Fixes crash and map UX for city guides
  CHANGELOG.md
  src/lib/Scenes/Map/GlobalMap.tsx
Labels: Merge On Green

#1716 [PURCHASE-1268] ArtworkDetails updates
  data/complete.queryMap.json
  src/__generated__/ArtworkDetails_artwork.graphql.ts
  src/__generated__/ArtworkQuery.graphql.ts
  src/lib/Scenes/Artwork/Components/ArtworkDetails.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ArtworkDetails-tests.tsx
Labels: Jira Synced, Merge On Green

#1722 PURCHASE-1261 - Fixes artwork title wrap
  src/lib/Scenes/Artwork/Components/ArtworkTombstone.tsx
Labels: Jira Synced

#1726 WIP: AUCT-472: Update copy on registration pending view
  CHANGELOG.md
  src/lib/Components/Bidding/Screens/RegistrationResult.tsx
  src/lib/Components/Bidding/Screens/__tests__/RegistrationResult-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/__snapshots__/RegistrationResult-tests.tsx.snap
Labels: Jira Synced

#1730 Update copy on credit card registration screen
  CHANGELOG.md
  src/lib/Components/Bidding/Components/PaymentInfo.tsx
  src/lib/Components/Bidding/Components/__tests__/__snapshots__/PaymentInfo-tests.tsx.snap
  src/lib/Components/Bidding/Screens/CreditCardForm.tsx
  src/lib/Components/Bidding/Screens/__tests__/CreditCardForm-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/__snapshots__/CreditCardForm-tests.tsx.snap
  src/lib/Components/Bidding/Screens/__tests__/__snapshots__/Registration-tests.tsx.snap
  src/lib/Containers/__tests__/__snapshots__/RegistrationFlow-tests.tsx.snap
Labels: Jira Synced, Merge On Green

#1728 PURCHASE-1272 - Replace all Emission Buttons with Palette Button
  CHANGELOG.md
  Example/Emission/AppDelegate.m
  Example/Podfile
  Example/Podfile.lock
  data/complete.queryMap.json
  data/schema.graphql
  src/__generated__/QueryRenderersSaleQuery.graphql.ts
  src/__generated__/SaleQuery.graphql.ts
  src/__generated__/SaleRefetchQuery.graphql.ts
  src/__generated__/Sale_sale.graphql.ts
  src/lib/Components/Artist/About.tsx
  src/lib/Components/Bidding/Components/Button.tsx
  src/lib/Components/Bidding/Components/__tests__/Button-tests.tsx
  src/lib/Components/Bidding/Components/__tests__/__snapshots__/Button-tests.tsx.snap
  src/lib/Components/Bidding/Screens/BidResult.tsx
  src/lib/Components/Bidding/Screens/BillingAddress.tsx
  src/lib/Components/Bidding/Screens/ConfirmBid.tsx
  src/lib/Components/Bidding/Screens/CreditCardForm.tsx
  src/lib/Components/Bidding/Screens/Registration.tsx
  src/lib/Components/Bidding/Screens/RegistrationResult.tsx
  src/lib/Components/Bidding/Screens/SelectMaxBid.tsx
  src/lib/Components/Bidding/Screens/SelectMaxBidEdit.tsx
  src/lib/Components/Bidding/Screens/__tests__/BidResult-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/BillingAddress-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/CreditCardForm-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/Registration-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/RegistrationResult-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/SelectMaxBid-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/__snapshots__/BillingAddress-tests.tsx.snap
  src/lib/Components/Bidding/Screens/__tests__/__snapshots__/CreditCardForm-tests.tsx.snap
  src/lib/Components/Bidding/Screens/__tests__/__snapshots__/Registration-tests.tsx.snap
  src/lib/Components/Bidding/Screens/__tests__/__snapshots__/RegistrationResult-tests.tsx.snap
  src/lib/Components/Bidding/Screens/__tests__/__snapshots__/SelectMaxBid-tests.tsx.snap
  src/lib/Components/Bidding/Screens/__tests__/__snapshots__/SelectMaxBidEdit-tests.tsx.snap
  src/lib/Components/Bidding/__tests__/BidFlow-tests.tsx
  src/lib/Components/Buttons/Button.tsx
  src/lib/Components/Buttons/NavigationButton.tsx
  src/lib/Components/Buttons/PrimaryBlack.tsx
  src/lib/Components/Buttons/__stories__/Buttons.story.tsx
  src/lib/Components/Buttons/__tests__/PrimaryBlack-tests.tsx
  src/lib/Components/Buttons/__tests__/__snapshots__/NavigationButton-tests.tsx.snap
  src/lib/Components/Buttons/__tests__/__snapshots__/PrimaryBlack-tests.tsx.snap
  src/lib/Components/Buttons/index.tsx
  src/lib/Components/Consignments/Components/FormElements.tsx
  src/lib/Components/Modal.tsx
  src/lib/Components/Text/PrimaryButtonText.tsx
  src/lib/Components/__tests__/__snapshots__/Modal-tests.tsx.snap
  src/lib/Containers/Gene.tsx
  src/lib/Containers/Sale.tsx
  src/lib/Containers/__stories__/Sale.story.tsx
  src/lib/Containers/__stories__/index.ts
  src/lib/Containers/__tests__/Gene-tests.tsx
  src/lib/Containers/__tests__/Sale-tests.tsx
  src/lib/Containers/__tests__/__snapshots__/BidFlow-tests.tsx.snap
  src/lib/Containers/__tests__/__snapshots__/RegistrationFlow-tests.tsx.snap
  src/lib/Containers/__tests__/__snapshots__/Sale-tests.tsx.snap
  src/lib/Containers/__tests__/index-tests.tsx
  src/lib/Containers/index.tsx
  src/lib/relay/QueryRenderers.tsx
Labels: Jira Synced

#1731 Update copy on returning registration view
  CHANGELOG.md
  src/lib/Components/Bidding/Screens/Registration.tsx
  src/lib/Components/Bidding/Screens/__tests__/Registration-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/__snapshots__/Registration-tests.tsx.snap
  src/lib/Containers/__tests__/__snapshots__/RegistrationFlow-tests.tsx.snap
Labels: Jira Synced, Merge On Green

#1708 [PURCHASE-1238, PURCHASE-1248] PartnerCard and SellerInfo adjustments
  CHANGELOG.md
  data/complete.queryMap.json
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/CommercialInformation_artwork.graphql.ts
  src/__generated__/SellerInfo_artwork.graphql.ts
  src/lib/Scenes/Artwork/Components/CommercialInformation.tsx
  src/lib/Scenes/Artwork/Components/PartnerCard.tsx
  src/lib/Scenes/Artwork/Components/SellerInfo.tsx
  src/lib/Scenes/Artwork/Components/__tests__/CommercialInformation-tests.tsx
  src/lib/Scenes/Artwork/Components/__tests__/PartnerCard-tests.tsx
  src/lib/Scenes/Artwork/Components/__tests__/SellerInfo-tests.tsx
Labels: Jira Synced

#1732 Add image thumbnail to the confirm bid screen
  CHANGELOG.md
  src/__generated__/BidFlowSelectMaxBidRendererQuery.graphql.ts
  src/__generated__/ConfirmBid_sale_artwork.graphql.ts
  src/__generated__/QueryRenderersBidFlowQuery.graphql.ts
  src/__generated__/SelectMaxBidRefetchQuery.graphql.ts
  src/lib/Components/Bidding/Screens/ConfirmBid.tsx
  src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/SelectMaxBid-tests.tsx
  src/lib/Components/Bidding/__stories__/BidFlow.story.tsx
  src/lib/Components/Bidding/__tests__/BidFlow-tests.tsx
Labels: Jira Synced, Merge On Green

#1733 Fix CI builds/deploy by changing back to Ruby 2.5.3
  .ruby-version
  CHANGELOG.md
  Example/.ruby-version
Labels: Merge On Green

#1721 [PURCHASE-1259, PURCHASE-1266, PURCHASE-1269, PURCHASE-1273] iOS artwork page small text and styling fixes
  data/complete.queryMap.json
  src/__generated__/ArtworkExtraLinks_artwork.graphql.ts
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/CommercialInformation_artwork.graphql.ts
  src/lib/Scenes/Artwork/Components/AboutWork.tsx
  src/lib/Scenes/Artwork/Components/ArtworkDetails.tsx
  src/lib/Scenes/Artwork/Components/ArtworkExtraLinks.tsx
  src/lib/Scenes/Artwork/Components/ArtworkTombstone.tsx
  src/lib/Scenes/Artwork/Components/CommercialInformation.tsx
  src/lib/Scenes/Artwork/Components/__stories__/AboutWork.story.tsx
  src/lib/Scenes/Artwork/Components/__tests__/AboutWork-tests.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ArtworkDetails-tests.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ArtworkExtraLinks-tests.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ArtworkTombstone-tests.tsx
Labels: Jira Synced

#1735 PURCHASE-1144 - Artwork Analytics
  .vscode/settings.json
  CHANGELOG.md
  Example/Emission/ARRootViewController.m
  Example/Podfile.lock
  Example/Pods/Pods.xcodeproj/project.pbxproj
  data/complete.queryMap.json
  package.json
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/ArtworkTombstoneStoryQuery.graphql.ts
  src/__generated__/Artwork_artwork.graphql.ts
  src/__generated__/FollowArtistButtonTestsErrorQuery.graphql.ts
  src/__generated__/FollowArtistButtonTestsQuery.graphql.ts
  src/__generated__/FollowArtistButton_artist.graphql.ts
  src/lib/Components/ArtistListItem.tsx
  src/lib/Components/Consignments/Screens/__tests__/Overview-analytics-tests.tsx
  src/lib/Components/Inbox/Conversations/Composer.tsx
  src/lib/Components/Inbox/Conversations/__tests__/Composer-tests.tsx
  src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Composer-tests.tsx.snap
  src/lib/Components/ReadMore.tsx
  src/lib/Components/__tests__/ReadMore-tests.tsx
  src/lib/Containers/__tests__/Conversation-tests.tsx
  src/lib/Scenes/Artwork/Artwork.tsx
  src/lib/Scenes/Artwork/Components/AboutArtist.tsx
  src/lib/Scenes/Artwork/Components/AboutWork.tsx
  src/lib/Scenes/Artwork/Components/ArtworkActions.tsx
  src/lib/Scenes/Artwork/Components/ArtworkDetails.tsx
  src/lib/Scenes/Artwork/Components/ArtworkExtraLinks.tsx
  src/lib/Scenes/Artwork/Components/ArtworkHistory.tsx
  src/lib/Scenes/Artwork/Components/ArtworkTombstone.tsx
  src/lib/Scenes/Artwork/Components/FollowArtistButton.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/__tests__/ImageCarousel-tests.tsx
  src/lib/Scenes/Artwork/Components/__tests__/FollowArtistButton-tests.tsx
  src/lib/Scenes/Artwork/__tests__/Artwork-tests.tsx
  src/lib/__fixtures__/ArtworkFixture.ts
  src/lib/utils/track/schema.ts
  storybook/storyLoader.js
  yarn.lock
Labels: Jira Synced

#1738 Remove .only and fix tests in ConfirmBid-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/__snapshots__/ConfirmBid-tests.tsx.snap
Labels: Jira Synced

#1742 Fixes an issue where placing a bid hangs
  CHANGELOG.md
  src/lib/Components/Bidding/Screens/ConfirmBid.tsx
  src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
Labels: Jira Synced

#1743 Display an error message when polling fails
  CHANGELOG.md
  src/lib/Components/Bidding/Screens/ConfirmBid.tsx
  src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
Labels: Jira Synced

#1744 Add more type checks
  src/__generated__/BidderPositionQuery.graphql.ts
  src/lib/Components/Bidding/Screens/ConfirmBid/BidderPositionQuery.ts
  src/lib/Components/Bidding/Screens/ConfirmBid/index.tsx
  src/lib/Components/Bidding/Screens/__tests__/ConfirmBid-tests.tsx
  src/lib/Components/Bidding/__stories__/BidFlow.story.tsx
  src/lib/Components/Bidding/__tests__/BidFlow-tests.tsx
Labels: Jira Synced

#1749 PURCHASE-1320 - Adds artwork grid analytics
  data/complete.queryMap.json
  data/schema.graphql
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/Artwork_artwork.graphql.ts
  src/__generated__/OtherWorks_artwork.graphql.ts
  src/lib/Components/ArtworkGrids/GenericGrid.tsx
  src/lib/Scenes/Artwork/Artwork.tsx
  src/lib/Scenes/Artwork/Components/OtherWorks/OtherWorks.tsx
  src/lib/Scenes/Artwork/Components/__tests__/OtherWorks-tests.tsx
  src/lib/utils/track/schema.ts
Labels: Jira Synced

#1751 [PURCHASE-1328, PURCHASE-1257, PURCHASE-1349] Small changes to padding and font size
  Pod/Classes/ViewControllers/ARArtworkAttributionClassFAQViewController.m
  src/lib/Scenes/Artwork/Components/ArtworkExtraLinks.tsx
  src/lib/Scenes/Artwork/Components/CommercialInformation.tsx
  src/lib/Scenes/ArtworkAttributionClassFAQ/ArtworkAttributionClassFAQ.tsx
  src/lib/Scenes/ArtworkAttributionClassFAQ/__tests__/ArtworkAttributionClassFAQ-tests.tsx
Labels: Jira Synced

#1745 WIP: [PURCHASE-1276] Adds RetryErrorBoundary, adds to Artwork page
  CHANGELOG.md
  src/lib/Components/RetryErrorBoundary.tsx
  src/lib/Components/__tests__/RetryErrorBoundary-tests.tsx
  src/lib/Components/__tests__/__snapshots__/RetryErrorBoundary-tests.tsx.snap
  src/lib/Scenes/Artwork/Artwork.tsx
Labels: Jira Synced, Merge On Green

#1756 [v2] Update after dropping deprecations
  CHANGELOG.md
  data/complete.queryMap.json
  data/schema.graphql
  src/__generated__/CitySectionListQuery.graphql.ts
  src/__generated__/CitySectionList_city.graphql.ts
  src/__generated__/MoreInfoQuery.graphql.ts
  src/__generated__/MoreInfoTestsQuery.graphql.ts
  src/__generated__/MoreInfo_show.graphql.ts
  src/__generated__/QueryRenderersCitySectionListQuery.graphql.ts
  src/__generated__/ShowEventSectionTestsQuery.graphql.ts
  src/__generated__/ShowEventSection_event.graphql.ts
  src/lib/Scenes/City/CitySectionList.tsx
  src/lib/Scenes/Show/Components/ShowEventSection.tsx
  src/lib/relay/QueryRenderers.tsx
Labels: Jira Synced

#1758 [PURCHASE-1323] Fixes problem with project file churn #trivial
  .circleci/config.yml
  .gitignore
  Example/Pods/Pods.xcodeproj/project.pbxproj
Labels: Merge On Green

#1760 PURCHASE-1359: Only display "View in Room" when the artwork is_hangable
  data/complete.queryMap.json
  src/__generated__/ArtworkActionsTestsErrorQuery.graphql.ts
  src/__generated__/ArtworkActionsTestsQuery.graphql.ts
  src/__generated__/ArtworkActions_artwork.graphql.ts
  src/__generated__/ArtworkQuery.graphql.ts
  src/lib/Scenes/Artwork/Components/ArtworkActions.tsx
  src/lib/Scenes/Artwork/Components/__stories__/ArtworkActions.story.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ArtworkActions-tests.tsx
Labels: Jira Synced
