Repository artsy/emission, pull requests merged in 2019-02, with the labels that each got.

#1286 LD-100 - Centers fair booth title and small adjustment to hours styling
  CHANGELOG.md
  src/lib/Components/HoursCollapsible.tsx
  src/lib/Scenes/Fair/Components/FairBoothPreview/Components/FairBoothPreviewHeader.tsx
  src/lib/Scenes/Fair/Screens/__tests__/__snapshots__/FairDetail-tests.tsx.snap
  src/lib/Scenes/Fair/__tests__/__snapshots__/Fair-tests.tsx.snap
Labels: Jira Synced

#1295 Fair styling
  CHANGELOG.md
  src/__generated__/FairDetailShowsQuery.graphql.ts
  src/__generated__/FairDetailShowsQuery.queryMap.json
  src/__generated__/FairDetailTestsQuery.graphql.ts
  src/__generated__/FairDetailTestsQuery.queryMap.json
  src/__generated__/FairDetail_fair.graphql.ts
  src/__generated__/FairQuery.graphql.ts
  src/__generated__/FairQuery.queryMap.json
  src/__generated__/FairTestsQuery.graphql.ts
  src/__generated__/FairTestsQuery.queryMap.json
  src/__generated__/QueryRenderersFairQuery.graphql.ts
  src/__generated__/QueryRenderersFairQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/__generated__/indexTestsQuery.graphql.ts
  src/__generated__/indexTestsQuery.queryMap.json
  src/lib/Scenes/Fair/Components/ArtistsExhibitorsWorksLink.tsx
  src/lib/Scenes/Fair/Components/FairBoothPreview/Components/FairBoothPreviewHeader.tsx
  src/lib/Scenes/Fair/Components/FairBoothPreview/Components/__tests__/__snapshots__/FairBoothPreviewHeader-tests.tsx.snap
  src/lib/Scenes/Fair/Components/FairBoothPreview/__tests__/__snapshots__/index-tests.tsx.snap
  src/lib/Scenes/Fair/Components/FairBoothPreview/__tests__/index-tests.tsx
  src/lib/Scenes/Fair/Components/FairBoothPreview/index.tsx
  src/lib/Scenes/Fair/Components/FairHeader/__tests__/__snapshots__/index-tests.tsx.snap
  src/lib/Scenes/Fair/Components/FairHeader/__tests__/index-tests.tsx
  src/lib/Scenes/Fair/Components/FairHeader/index.tsx
  src/lib/Scenes/Fair/Components/__tests__/__snapshots__/ArtistsExhibitorsWorksLink-tests.tsx.snap
  src/lib/Scenes/Fair/Screens/FairDetail.tsx
  src/lib/Scenes/Fair/Screens/__tests__/__snapshots__/FairDetail-tests.tsx.snap
  src/lib/Scenes/Fair/__tests__/__snapshots__/Fair-tests.tsx.snap
Labels: Jira Synced

#1298 LD-182 - Show address updates
  CHANGELOG.md
  data/schema.graphql
  src/__generated__/DetailTestsQuery.graphql.ts
  src/__generated__/DetailTestsQuery.queryMap.json
  src/__generated__/Detail_show.graphql.ts
  src/__generated__/FairDetailShowsQuery.graphql.ts
  src/__generated__/FairDetailShowsQuery.queryMap.json
  src/__generated__/FairDetailTestsQuery.graphql.ts
  src/__generated__/FairDetailTestsQuery.queryMap.json
  src/__generated__/FairQuery.graphql.ts
  src/__generated__/FairQuery.queryMap.json
  src/__generated__/FairTestsQuery.graphql.ts
  src/__generated__/FairTestsQuery.queryMap.json
  src/__generated__/LocationMap_location.graphql.ts
  src/__generated__/QueryRenderersFairQuery.graphql.ts
  src/__generated__/QueryRenderersFairQuery.queryMap.json
  src/__generated__/QueryRenderersShowQuery.graphql.ts
  src/__generated__/QueryRenderersShowQuery.queryMap.json
  src/__generated__/ShowQuery.graphql.ts
  src/__generated__/ShowQuery.queryMap.json
  src/__generated__/ShowTestsQuery.graphql.ts
  src/__generated__/ShowTestsQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/lib/Components/LocationMap/__tests__/__snapshots__/index-tests.tsx.snap
  src/lib/Components/LocationMap/index.tsx
  src/lib/Scenes/Fair/Screens/__tests__/__snapshots__/FairDetail-tests.tsx.snap
  src/lib/Scenes/Fair/__tests__/__snapshots__/Fair-tests.tsx.snap
  src/lib/Scenes/Show/Screens/Detail.tsx
Labels: Jira Synced

#1293 Enable Saving Fairs
  CHANGELOG.md
  Example/Emission/main.m
  src/__generated__/FairDetailShowsQuery.graphql.ts
  src/__generated__/FairDetailShowsQuery.queryMap.json
  src/__generated__/FairDetailTestsQuery.graphql.ts
  src/__generated__/FairDetailTestsQuery.queryMap.json
  src/__generated__/FairHeaderMutation.graphql.ts
  src/__generated__/FairHeaderMutation.queryMap.json
  src/__generated__/FairHeaderTestsQuery.graphql.ts
  src/__generated__/FairHeaderTestsQuery.queryMap.json
  src/__generated__/FairHeader_fair.graphql.ts
  src/__generated__/FairQuery.graphql.ts
  src/__generated__/FairQuery.queryMap.json
  src/__generated__/FairTestsQuery.graphql.ts
  src/__generated__/FairTestsQuery.queryMap.json
  src/__generated__/QueryRenderersFairQuery.graphql.ts
  src/__generated__/QueryRenderersFairQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/lib/Components/Buttons/InvertedButton.tsx
  src/lib/Components/Buttons/__tests__/__snapshots__/InvertedButton-tests.tsx.snap
  src/lib/Components/Home/ArtistRails/__tests__/__snapshots__/ArtistCard-tests.tsx.snap
  src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/Message-tests.tsx.snap
  src/lib/Scenes/Fair/Components/FairHeader/index.tsx
  src/lib/Scenes/Fair/Screens/__tests__/__snapshots__/FairDetail-tests.tsx.snap
  src/lib/Scenes/Fair/__fixtures__/index.ts
  src/lib/Scenes/Fair/__tests__/__snapshots__/Fair-tests.tsx.snap
  src/lib/Scenes/Show/Components/ShowHeader/__tests__/__snapshots__/ShowHeader-tests.tsx.snap
Labels: Jira Synced

#1303 LD-189 - EntityList partner links
  CHANGELOG.md
  src/__generated__/FairDetailShowsQuery.graphql.ts
  src/__generated__/FairDetailShowsQuery.queryMap.json
  src/__generated__/FairDetailTestsQuery.graphql.ts
  src/__generated__/FairDetailTestsQuery.queryMap.json
  src/__generated__/FairHeader_fair.graphql.ts
  src/__generated__/FairQuery.graphql.ts
  src/__generated__/FairQuery.queryMap.json
  src/__generated__/FairTestsQuery.graphql.ts
  src/__generated__/FairTestsQuery.queryMap.json
  src/__generated__/QueryRenderersFairQuery.graphql.ts
  src/__generated__/QueryRenderersFairQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/__generated__/indexTestsFairHeaderQuery.graphql.ts
  src/__generated__/indexTestsFairHeaderQuery.queryMap.json
  src/lib/Scenes/Fair/Components/FairHeader/index.tsx
  src/lib/Scenes/Fair/Fair.tsx
Labels: Jira Synced

#1308 Fixes update metaphysics querymap script
  scripts/merge-graphql-query-map.js
Labels: Merge On Green

#1321 Fair QA - Artworks grid page
  CHANGELOG.md
  src/__generated__/FairArtworksQuery.graphql.ts
  src/__generated__/FairArtworksQuery.queryMap.json
  src/__generated__/FairArtworksRefetchQuery.graphql.ts
  src/__generated__/FairArtworksRefetchQuery.queryMap.json
  src/__generated__/FairArtworksTestsQuery.graphql.ts
  src/__generated__/FairArtworksTestsQuery.queryMap.json
  src/__generated__/FairArtworks_fair.graphql.ts
  src/__generated__/FairHeaderMutation.graphql.ts
  src/__generated__/FairHeaderMutation.queryMap.json
  src/__generated__/FairQuery.graphql.ts
  src/__generated__/FairQuery.queryMap.json
  src/__generated__/FairTestsQuery.graphql.ts
  src/__generated__/FairTestsQuery.queryMap.json
  src/__generated__/Fair_fair.graphql.ts
  src/__generated__/QueryRenderersFairQuery.graphql.ts
  src/__generated__/QueryRenderersFairQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/lib/Components/ArtworkGrids/Artwork.tsx
  src/lib/Components/ArtworkGrids/InfiniteScrollGrid.tsx
  src/lib/Components/ArtworkGrids/__tests__/__snapshots__/Artwork-tests.tsx.snap
  src/lib/Components/ArtworkGrids/__tests__/__snapshots__/GenericGrid-tests.tsx.snap
  src/lib/Components/FilteredInfiniteScrollGrid/FilteredInfiniteScrollGrid.tsx
  src/lib/Components/Show/__tests__/__snapshots__/ShowArtworks-tests.tsx.snap
  src/lib/Scenes/Fair/Fair.tsx
  src/lib/Scenes/Fair/Screens/FairArtworks.tsx
  src/lib/Scenes/Fair/Screens/__tests__/__snapshots__/FairArtworks-tests.tsx.snap
Labels: Jira Synced

#1318 LD-205 - Adds Follow functionality to Fair exhibitors
  CHANGELOG.md
  package.json
  src/__generated__/FairBoothHeaderMutation.graphql.ts
  src/__generated__/FairBoothHeaderMutation.queryMap.json
  src/__generated__/FairBoothHeaderTestsQuery.graphql.ts
  src/__generated__/FairBoothHeaderTestsQuery.queryMap.json
  src/__generated__/FairBoothHeader_show.graphql.ts
  src/__generated__/FairBoothPreviewMutation.graphql.ts
  src/__generated__/FairBoothPreviewMutation.queryMap.json
  src/__generated__/FairBoothPreview_show.graphql.ts
  src/__generated__/FairBoothQuery.graphql.ts
  src/__generated__/FairBoothQuery.queryMap.json
  src/__generated__/FairBoothTestsQuery.graphql.ts
  src/__generated__/FairBoothTestsQuery.queryMap.json
  src/__generated__/FairDetailShowsQuery.graphql.ts
  src/__generated__/FairDetailShowsQuery.queryMap.json
  src/__generated__/FairDetailTestsQuery.graphql.ts
  src/__generated__/FairDetailTestsQuery.queryMap.json
  src/__generated__/FairQuery.graphql.ts
  src/__generated__/FairQuery.queryMap.json
  src/__generated__/FairTestsQuery.graphql.ts
  src/__generated__/FairTestsQuery.queryMap.json
  src/__generated__/QueryRenderersFairQuery.graphql.ts
  src/__generated__/QueryRenderersFairQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/__generated__/indexTestsFairBothPreviewQuery.graphql.ts
  src/__generated__/indexTestsFairBothPreviewQuery.queryMap.json
  src/lib/Scenes/Fair/Components/FairBoothHeader.tsx
  src/lib/Scenes/Fair/Components/FairBoothPreview/Components/FairBoothPreviewHeader.tsx
  src/lib/Scenes/Fair/Components/FairBoothPreview/index.tsx
  src/lib/Scenes/Fair/Components/__tests__/FairBoothHeader-tests.tsx
  src/lib/Scenes/Fair/Components/__tests__/__snapshots__/FairBoothHeader-tests.tsx.snap
  src/lib/Scenes/Fair/Screens/FairBooth.tsx
  src/lib/Scenes/Fair/Screens/__tests__/FairBooth-tests.tsx
  src/lib/Scenes/Fair/Screens/__tests__/FairDetail-tests.tsx
  src/lib/Scenes/Fair/Screens/__tests__/__snapshots__/FairBooth-tests.tsx.snap
  src/lib/Scenes/Fair/__tests__/Fair-tests.tsx
  src/lib/Scenes/Fair/__tests__/__snapshots__/Fair-tests.tsx.snap
Labels: Jira Synced

#1314 Global saves view ld153
  CHANGELOG.md
  src/__generated__/FairsQuery.graphql.ts
  src/__generated__/FairsQuery.queryMap.json
  src/__generated__/Fairs_me.graphql.ts
  src/__generated__/FavoriteFairsQuery.graphql.ts
  src/__generated__/FavoriteFairsQuery.queryMap.json
  src/__generated__/FavoriteShowsQuery.graphql.ts
  src/__generated__/FavoriteShowsQuery.queryMap.json
  src/__generated__/SavedFairItemRowMutation.graphql.ts
  src/__generated__/SavedFairItemRowMutation.queryMap.json
  src/__generated__/ShowsQuery.graphql.ts
  src/__generated__/ShowsQuery.queryMap.json
  src/__generated__/Shows_me.graphql.ts
  src/__generated__/complete.queryMap.json
  src/lib/Components/Lists/SavedFairItemRow.tsx
  src/lib/Components/ScrollableTabBar.tsx
  src/lib/Scenes/Favorites/Components/Fairs/Relay/FavoriteFairs.tsx
  src/lib/Scenes/Favorites/Components/Fairs/index.tsx
  src/lib/Scenes/Favorites/Components/Shows/Relay/FavoriteShows.tsx
  src/lib/Scenes/Favorites/Components/Shows/index.tsx
  src/lib/Scenes/Favorites/index.tsx
  src/lib/data/fonts.ts
  src/lib/utils/track.ts
Labels: Jira Synced

#1325 FairBooth routing
  CHANGELOG.md
  Example/Emission/AppDelegate.m
  Example/Podfile.lock
  Pod/Classes/ViewControllers/ARFairBoothComponentViewController.h
  Pod/Classes/ViewControllers/ARFairBoothComponentViewController.m
  data/schema.graphql
  src/__generated__/ArtistQuery.graphql.ts
  src/__generated__/ArtistQuery.queryMap.json
  src/__generated__/ArtistShow_show.graphql.ts
  src/__generated__/FairExhibitorsQuery.graphql.ts
  src/__generated__/FairExhibitorsQuery.queryMap.json
  src/__generated__/FairExhibitorsTestsQuery.graphql.ts
  src/__generated__/FairExhibitorsTestsQuery.queryMap.json
  src/__generated__/QueryRenderersArtistQuery.graphql.ts
  src/__generated__/QueryRenderersArtistQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/lib/AppRegistry.tsx
  src/lib/Components/Artist/Shows/ArtistShow.tsx
  src/lib/Scenes/Fair/Components/FairHeader/index.tsx
  src/lib/Scenes/Fair/Fair.tsx
  src/lib/Scenes/Fair/Screens/FairBooth.tsx
  src/lib/Scenes/Fair/Screens/FairExhibitors.tsx
  src/lib/Scenes/Fair/Screens/__tests__/FairExhibitors-tests.tsx
  src/lib/Scenes/Fair/Screens/__tests__/__snapshots__/FairExhibitors-tests.tsx.snap
Labels: Jira Synced

#1331 Enable viewing saved shows in global saves/follows view
  CHANGELOG.md
  src/__generated__/FavoriteShowsQuery.graphql.ts
  src/__generated__/FavoriteShowsQuery.queryMap.json
  src/__generated__/SavedShowItemRowMutation.graphql.ts
  src/__generated__/SavedShowItemRowMutation.queryMap.json
  src/__generated__/ShowsQuery.graphql.ts
  src/__generated__/ShowsQuery.queryMap.json
  src/__generated__/Shows_me.graphql.ts
  src/__generated__/complete.queryMap.json
  src/lib/Components/Lists/SavedShowItemRow.tsx
  src/lib/Scenes/Favorites/Components/Shows/index.tsx
Labels: Jira Synced

#1334 Fixes rendering markdown in Fair/Show (but also everywhere else
  CHANGELOG.md
  package.json
  src/lib/Components/Bidding/Screens/__tests__/__snapshots__/RegistrationResult-tests.tsx.snap
  src/lib/Components/Markdown.tsx
  src/lib/Components/__tests__/Markdown-tests.tsx
  yarn.lock
Labels: Jira Synced

#1332 LD-238 - Adds spacer between fair entities
  CHANGELOG.md
  src/lib/Scenes/Fair/Components/FairHeader/index.tsx
Labels: Jira Synced

#1333 Global Saves&Follows tracking, SavedShowItemRow fragmentification
  CHANGELOG.md
  src/__generated__/FavoriteShowsQuery.graphql.ts
  src/__generated__/FavoriteShowsQuery.queryMap.json
  src/__generated__/SavedShowItemRow_show.graphql.ts
  src/__generated__/ShowsQuery.graphql.ts
  src/__generated__/ShowsQuery.queryMap.json
  src/__generated__/Shows_me.graphql.ts
  src/__generated__/complete.queryMap.json
  src/lib/Components/Lists/SavedShowItemRow.tsx
  src/lib/Scenes/Favorites/Components/Shows/index.tsx
  src/lib/Scenes/Favorites/index.tsx
Labels: Jira Synced

#1341 Add cursor saved shows
  src/__generated__/FavoriteShowsQuery.graphql.ts
  src/__generated__/FavoriteShowsQuery.queryMap.json
  src/__generated__/ShowsQuery.graphql.ts
  src/__generated__/ShowsQuery.queryMap.json
  src/__generated__/Shows_me.graphql.ts
  src/__generated__/complete.queryMap.json
  src/lib/Scenes/Favorites/Components/Shows/index.tsx
Labels: Jira Synced

#1342 Adds display date to CountDownTimer
  CHANGELOG.md
  src/lib/Scenes/Fair/Components/FairHeader/CountdownTimer.tsx
  src/lib/Scenes/Fair/Components/FairHeader/__tests__/CountdownTimer-tests.tsx
  src/lib/Scenes/Fair/Components/FairHeader/index.tsx
Labels: Jira Synced

#1344 Adds dates of currently running saved shows to Global Saves + Follows
  CHANGELOG.md
  src/__generated__/FavoriteShowsQuery.graphql.ts
  src/__generated__/FavoriteShowsQuery.queryMap.json
  src/__generated__/SavedShowItemRow_show.graphql.ts
  src/__generated__/ShowsQuery.graphql.ts
  src/__generated__/ShowsQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/lib/Components/Lists/SavedShowItemRow.tsx
Labels: Jira Synced

#1345 Moves Fair sub screens to separate Native VCs
  CHANGELOG.md
  Example/Emission/AppDelegate.m
  Example/Podfile.lock
  Pod/Classes/ViewControllers/ARFairArtistsComponentViewController.h
  Pod/Classes/ViewControllers/ARFairArtistsComponentViewController.m
  Pod/Classes/ViewControllers/ARFairArtworksComponentViewController.h
  Pod/Classes/ViewControllers/ARFairArtworksComponentViewController.m
  Pod/Classes/ViewControllers/ARFairExhibitorsComponentViewController.h
  Pod/Classes/ViewControllers/ARFairExhibitorsComponentViewController.m
  package.json
  src/lib/AppRegistry.tsx
  src/lib/Components/Artist/Shows/ArtistShow.tsx
  src/lib/Components/HoursCollapsible.tsx
  src/lib/Scenes/Fair/Components/FairHeader/index.tsx
  src/lib/Scenes/Fair/Fair.tsx
  src/lib/Scenes/Fair/Screens/FairDetail.tsx
  src/lib/Scenes/Fair/Screens/FairExhibitors.tsx
  src/lib/Scenes/Fair/index.ts
  src/lib/Scenes/Show/Screens/Detail.tsx
  src/lib/utils/track.ts
Labels: Jira Synced, Merge On Green

#1346 Adds a sentry logger to the Emission app
  CHANGELOG.md
  Example/Emission.xcodeproj/project.pbxproj
  Example/Emission/ARAdminSentryBreadcrumbViewController.h
  Example/Emission/ARAdminSentryBreadcrumbViewController.m
  Example/Emission/ARRootViewController.m
  Example/Emission/AppDelegate.m
  Example/Podfile
  Example/Podfile.lock
Labels: Merge On Green

#1349 Improve the placeholder for a show
  CHANGELOG.md
  src/lib/Icons/Pin.tsx
  src/lib/Scenes/Show/Components/Shows/Components/ShowItem.tsx
  src/lib/Scenes/Show/Components/Shows/Components/__tests__/__snapshots__/ShowItem-tests.tsx.snap
  src/lib/Scenes/Show/Components/Shows/__tests__/__snapshots__/index-tests.tsx.snap
Labels: Jira Synced, Merge On Green

#1352 Make sure event name is ellipsis(ed?)
  CHANGELOG.md
  src/lib/Scenes/City/Components/Event/index.tsx
Labels: Jira Synced, Merge On Green

#1347 Fixes partner link on Fair booth header
  CHANGELOG.md
  src/__generated__/DetailTestsQuery.graphql.ts
  src/__generated__/DetailTestsQuery.queryMap.json
  src/__generated__/FairBoothHeaderTestsQuery.graphql.ts
  src/__generated__/FairBoothHeaderTestsQuery.queryMap.json
  src/__generated__/FairBoothHeader_show.graphql.ts
  src/__generated__/FairBoothQuery.graphql.ts
  src/__generated__/FairBoothQuery.queryMap.json
  src/__generated__/FairBoothTestsQuery.graphql.ts
  src/__generated__/FairBoothTestsQuery.queryMap.json
  src/__generated__/QueryRenderersShowQuery.graphql.ts
  src/__generated__/QueryRenderersShowQuery.queryMap.json
  src/__generated__/ShowHeader_show.graphql.ts
  src/__generated__/ShowQuery.graphql.ts
  src/__generated__/ShowQuery.queryMap.json
  src/__generated__/ShowTestsQuery.graphql.ts
  src/__generated__/ShowTestsQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/lib/Scenes/Fair/Components/FairBoothHeader.tsx
  src/lib/Scenes/Fair/Components/SearchLink.tsx
  src/lib/Scenes/Show/Components/ShowHeader/ShowHeader.tsx
  src/lib/Scenes/Show/Screens/Detail.tsx
Labels: Jira Synced

#1350 Fix timezone tests
  src/lib/Scenes/Fair/Components/FairHeader/__tests__/CountdownTimer-tests.tsx
Labels: Merge On Green

#1353 Adds clickable links for a map preview
  CHANGELOG.md
  Emission.podspec
  Example/Podfile.lock
  package.json
  src/lib/Components/LocationMap/__tests__/__snapshots__/index-tests.tsx.snap
  src/lib/Components/LocationMap/index.tsx
Labels: Jira Synced

#1354 Fixes follow button.
  CHANGELOG.md
  src/lib/Scenes/Fair/Components/FairBoothHeader.tsx
Labels: Jira Synced

#1360 LD-297 - Fixes fairbooth artworks count in fair view
  CHANGELOG.md
  src/__generated__/FairBoothPreview_show.graphql.ts
  src/__generated__/FairDetailShowsQuery.graphql.ts
  src/__generated__/FairDetailShowsQuery.queryMap.json
  src/__generated__/FairDetailTestsQuery.graphql.ts
  src/__generated__/FairDetailTestsQuery.queryMap.json
  src/__generated__/FairQuery.graphql.ts
  src/__generated__/FairQuery.queryMap.json
  src/__generated__/FairTestsQuery.graphql.ts
  src/__generated__/FairTestsQuery.queryMap.json
  src/__generated__/QueryRenderersFairQuery.graphql.ts
  src/__generated__/QueryRenderersFairQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/__generated__/indexTestsFairBothPreviewQuery.graphql.ts
  src/__generated__/indexTestsFairBothPreviewQuery.queryMap.json
  src/lib/Scenes/Fair/Components/FairBoothPreview/index.tsx
Labels: Jira Synced

#1359 [Map] Update fairs query as per latest schema.
  Example/Emission.xcodeproj/xcshareddata/xcschemes/Emission.xcscheme
  data/schema.graphql
  src/__generated__/GlobalMapRefetchQuery.graphql.ts
  src/__generated__/GlobalMapRefetchQuery.queryMap.json
  src/__generated__/GlobalMapTestsQuery.graphql.ts
  src/__generated__/GlobalMapTestsQuery.queryMap.json
  src/__generated__/GlobalMap_viewer.graphql.ts
  src/__generated__/MapRendererQuery.graphql.ts
  src/__generated__/MapRendererQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/lib/Scenes/Map/GlobalMap.tsx
Labels: Jira Synced

#1364 Adds more markdown rendering options
  src/lib/Components/Bidding/Screens/__tests__/__snapshots__/RegistrationResult-tests.tsx.snap
  src/lib/Components/Markdown.tsx
  src/lib/Components/__tests__/Markdown-tests.tsx
  src/lib/Scenes/Fair/__stories__/Fair.story.tsx
Labels: Merge On Green

#1365 Fixes fair view crash on fairs with no profiles #trivial
  CHANGELOG.md
  src/lib/Scenes/Fair/Components/FairHeader/index.tsx
Labels: Merge On Green

#1367 various analytics updates & changes
  CHANGELOG.md
  src/__generated__/DetailTestsQuery.graphql.ts
  src/__generated__/DetailTestsQuery.queryMap.json
  src/__generated__/FairBoothQuery.graphql.ts
  src/__generated__/FairBoothQuery.queryMap.json
  src/__generated__/FairBoothTestsQuery.graphql.ts
  src/__generated__/FairBoothTestsQuery.queryMap.json
  src/__generated__/QueryRenderersShowArtistsQuery.graphql.ts
  src/__generated__/QueryRenderersShowArtistsQuery.queryMap.json
  src/__generated__/QueryRenderersShowArtworksQuery.graphql.ts
  src/__generated__/QueryRenderersShowArtworksQuery.queryMap.json
  src/__generated__/QueryRenderersShowQuery.graphql.ts
  src/__generated__/QueryRenderersShowQuery.queryMap.json
  src/__generated__/ShowArtistsPreviewTestsQuery.graphql.ts
  src/__generated__/ShowArtistsPreviewTestsQuery.queryMap.json
  src/__generated__/ShowArtistsPreview_show.graphql.ts
  src/__generated__/ShowArtistsTestsQuery.graphql.ts
  src/__generated__/ShowArtistsTestsQuery.queryMap.json
  src/__generated__/ShowArtists_show.graphql.ts
  src/__generated__/ShowArtworksRefetchQuery.graphql.ts
  src/__generated__/ShowArtworksRefetchQuery.queryMap.json
  src/__generated__/ShowArtworksTestsQuery.graphql.ts
  src/__generated__/ShowArtworksTestsQuery.queryMap.json
  src/__generated__/ShowArtworks_show.graphql.ts
  src/__generated__/ShowQuery.graphql.ts
  src/__generated__/ShowQuery.queryMap.json
  src/__generated__/ShowTestsQuery.graphql.ts
  src/__generated__/ShowTestsQuery.queryMap.json
  src/__generated__/complete.queryMap.json
  src/lib/AppRegistry.tsx
  src/lib/Components/FilteredInfiniteScrollGrid/FilteredInfiniteScrollGrid.tsx
  src/lib/Components/Show/ShowArtists.tsx
  src/lib/Components/Show/ShowArtistsPreview.tsx
  src/lib/Components/Show/ShowArtworks.tsx
  src/lib/Scenes/Fair/Screens/FairArtworks.tsx
  src/lib/Scenes/Fair/Screens/FairMoreInfo.tsx
  src/lib/Scenes/Fair/Screens/__tests__/__snapshots__/FairMoreInfo-tests.tsx.snap
  src/lib/Scenes/Show/Components/ShowHeader/ShowHeader.tsx
  src/lib/Scenes/Show/Screens/Detail.tsx
  src/lib/Scenes/Show/Screens/MoreInfo.tsx
  src/lib/utils/track.ts
Labels: Merge On Green
