Repository artsy/emission, pull requests merged in 2019-09, with the labels that each got.

#1785 [PURCHASE-1358] Attribution class FAQ is cut off
  src/lib/Scenes/ArtworkAttributionClassFAQ/ArtworkAttributionClassFAQ.tsx
Labels: Jira Synced

#1830 [v2] Make all of emission use Relay
  CHANGELOG.md
  data/complete.queryMap.json
  data/schema.graphql
  src/__generated__/ArtistCard_artist.graphql.ts
  src/__generated__/ArtistListItemFollowArtistMutation.graphql.ts
  src/__generated__/ArtistRailFollowMutation.graphql.ts
  src/__generated__/ArtistRail_rail.graphql.ts
  src/__generated__/ConsignmentsArtistQuery.graphql.ts
  src/__generated__/FollowArtistButtonMutation.graphql.ts
  src/__generated__/ForYouRefetchQuery.graphql.ts
  src/__generated__/QueryRenderersForYouQuery.graphql.ts
  src/__generated__/TimeOffsetProviderQuery.graphql.ts
  src/__generated__/addAssetToConsignmentMutation.graphql.ts
  src/__generated__/createConsignmentSubmissionMutation.graphql.ts
  src/__generated__/createGeminiAssetWithS3CredentialsMutation.graphql.ts
  src/__generated__/getConvectionGeminiKeyQuery.graphql.ts
  src/__generated__/getGeminiCredentialsForEnvironmentMutation.graphql.ts
  src/__generated__/updateConsignmentSubmissionMutation.graphql.ts
  src/lib/Components/Bidding/Context/TimeOffsetProvider.tsx
  src/lib/Components/Bidding/Context/__tests__/TimeOffsetProvider-tests.tsx
  src/lib/Components/Bidding/Screens/__tests__/Registration-tests.tsx
  src/lib/Components/Consignments/Components/__tests__/ArtworkConsignmentTodo-tests.tsx
  src/lib/Components/Consignments/Screens/ConsignmentsArtist.tsx
  src/lib/Components/Consignments/Screens/Metadata.tsx
  src/lib/Components/Consignments/Screens/Overview.tsx
  src/lib/Components/Consignments/Screens/__tests__/ConsignmentsArtist-tests.tsx
  src/lib/Components/Consignments/Screens/__tests__/Metadata-tests.tsx
  src/lib/Components/Consignments/Screens/__tests__/Overview-analytics-tests.tsx
  src/lib/Components/Consignments/Screens/__tests__/Overview-local-storage-tests.tsx
  src/lib/Components/Consignments/Screens/__tests__/Overview-uploading-tests.tsx
  src/lib/Components/Consignments/Screens/__tests__/__snapshots__/Metadata-tests.tsx.snap
  src/lib/Components/Consignments/Submission/Gemini/createGeminiAssetWithS3Credentials.ts
  src/lib/Components/Consignments/Submission/Gemini/getConvectionGeminiKey.ts
  src/lib/Components/Consignments/Submission/Gemini/getGeminiCredentialsForEnvironment.ts
  src/lib/Components/Consignments/Submission/__tests__/consignmentSetupToSubmission-tests.ts
  src/lib/Components/Consignments/Submission/__tests__/create-tests.ts
  src/lib/Components/Consignments/Submission/__tests__/geminiUploadToS3-tests.ts
  src/lib/Components/Consignments/Submission/__tests__/objectToGraphQL-tests.ts
  src/lib/Components/Consignments/Submission/__tests__/update-tests.ts
  src/lib/Components/Consignments/Submission/__tests__/uploadPhotoToGemini-tests.ts
  src/lib/Components/Consignments/Submission/addAssetToConsignment.ts
  src/lib/Components/Consignments/Submission/consignmentSetupToSubmission.ts
  src/lib/Components/Consignments/Submission/create.ts
  src/lib/Components/Consignments/Submission/createConsignmentSubmission.ts
  src/lib/Components/Consignments/Submission/geminiUploadToS3.ts
  src/lib/Components/Consignments/Submission/objectToGraphQL.ts
  src/lib/Components/Consignments/Submission/types.ts
  src/lib/Components/Consignments/Submission/update.ts
  src/lib/Components/Consignments/Submission/updateConsignmentSubmission.ts
  src/lib/Components/Consignments/Submission/uploadPhotoToGemini.ts
  src/lib/Components/Consignments/__stories__/consignmentSetups.ts
  src/lib/Components/Consignments/index.tsx
  src/lib/Components/Home/ArtistRails/ArtistCard.tsx
  src/lib/Components/Home/ArtistRails/ArtistRail.tsx
  src/lib/Components/Home/ArtistRails/__tests__/ArtistCard-tests.tsx
  src/lib/__tests__/metaphysics-tests.ts
  src/lib/metaphysics.ts
Labels: Consignments, Jira Synced

#1835 PURCHASE-1411 Prefetch images
  Pod/Classes/OpaqueImageViewComponent/AROpaqueImageViewManager.m
  src/lib/Components/OpaqueImageView/OpaqueImageView.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarouselEmbedded.tsx
  src/setupJest.ts
Labels: Jira Synced

#1832 Fixes Artist Header & Gene Header Follow buttons
  CHANGELOG.md
  data/complete.queryMap.json
  src/__generated__/ArtistHeaderQuery.graphql.ts
  src/__generated__/ArtistQuery.graphql.ts
  src/__generated__/FairArtworksQuery.graphql.ts
  src/__generated__/FairArtworksTestsQuery.graphql.ts
  src/__generated__/FairBoothQuery.graphql.ts
  src/__generated__/FairBoothTestsQuery.graphql.ts
  src/__generated__/FilteredInfiniteScrollGridQuery.graphql.ts
  src/__generated__/FilteredInfiniteScrollGrid_entity.graphql.ts
  src/__generated__/GeneQuery.graphql.ts
  src/__generated__/HeaderFollowArtistMutation.graphql.ts
  src/__generated__/HeaderFollowGeneMutation.graphql.ts
  src/__generated__/Header_artist.graphql.ts
  src/__generated__/Header_gene.graphql.ts
  src/__generated__/QueryRenderersArtistQuery.graphql.ts
  src/__generated__/QueryRenderersGeneQuery.graphql.ts
  src/__generated__/ShowArtworksQuery.graphql.ts
  src/__generated__/ShowArtworksTestsQuery.graphql.ts
  src/lib/Components/Artist/Header.tsx
  src/lib/Components/ArtistListItem.tsx
  src/lib/Components/FilteredInfiniteScrollGrid/FilteredInfiniteScrollGrid.tsx
  src/lib/Components/Gene/Header.tsx
  src/lib/Containers/Artist.tsx
  src/lib/Containers/Gene.tsx
  src/lib/Containers/__tests__/Artist-tests.tsx
  src/lib/Containers/__tests__/__snapshots__/Artist-tests.tsx.snap
  src/lib/Scenes/Fair/Screens/FairBooth.tsx
Labels: Merge On Green

#1834 PURCHASE-1393 & PURCHASE-1449
  Example/Emission/ARRootViewController.m
  data/complete.queryMap.json
  src/__generated__/ArtworkExtraLinks_artwork.graphql.ts
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/AuctionPriceTestsQuery.graphql.ts
  src/__generated__/AuctionPrice_artwork.graphql.ts
  src/lib/Scenes/Artwork/Components/ArtworkExtraLinks.tsx
  src/lib/Scenes/Artwork/Components/AuctionPrice.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ArtworkExtraLinks-tests.tsx
Labels: Jira Synced

#1823 Updates README
  README.md
Labels: Merge On Green

#1831 [v2] Remove more root fields
  CHANGELOG.md
  data/complete.queryMap.json
  data/schema.graphql
  src/__generated__/ArtistForSaleArtworksGridQuery.graphql.ts
  src/__generated__/ArtistNotForSaleArtworksGridQuery.graphql.ts
  src/__generated__/ArtistQuery.graphql.ts
  src/__generated__/BidFlowSelectMaxBidRendererQuery.graphql.ts
  src/__generated__/FairArtworksQuery.graphql.ts
  src/__generated__/FairArtworksTestsQuery.graphql.ts
  src/__generated__/FairBoothQuery.graphql.ts
  src/__generated__/FairBoothTestsQuery.graphql.ts
  src/__generated__/FilteredInfiniteScrollGridQuery.graphql.ts
  src/__generated__/GeneQuery.graphql.ts
  src/__generated__/LotsByFollowedArtistsQuery.graphql.ts
  src/__generated__/LotsByFollowedArtists_query.graphql.ts
  src/__generated__/QueryRenderersArtistQuery.graphql.ts
  src/__generated__/QueryRenderersBidFlowQuery.graphql.ts
  src/__generated__/QueryRenderersGeneQuery.graphql.ts
  src/__generated__/SalesQuery.graphql.ts
  src/__generated__/SalesRendererQuery.graphql.ts
  src/__generated__/Sales_query.graphql.ts
  src/__generated__/SelectMaxBidRefetchQuery.graphql.ts
  src/__generated__/SelectMaxBid_sale_artwork.graphql.ts
  src/__generated__/ShowArtworksQuery.graphql.ts
  src/__generated__/ShowArtworksTestsQuery.graphql.ts
  src/lib/Components/Bidding/Screens/SelectMaxBid.tsx
  src/lib/Components/Bidding/Screens/__tests__/SelectMaxBid-tests.tsx
  src/lib/Components/Bidding/__stories__/BidFlow.story.tsx
  src/lib/Scenes/Home/Components/Sales/Components/LotsByFollowedArtists.tsx
  src/lib/Scenes/Home/Components/Sales/Components/SaleList.tsx
  src/lib/Scenes/Home/Components/Sales/Components/SectionHeader.tsx
  src/lib/Scenes/Home/Components/Sales/Components/__tests__/LotsByFollowedArtists-tests.tsx
  src/lib/Scenes/Home/Components/Sales/__tests__/__snapshots__/index-tests.tsx.snap
  src/lib/Scenes/Home/Components/Sales/__tests__/index-tests.tsx
  src/lib/Scenes/Home/Components/Sales/index.tsx
Labels: Jira Synced, Merge On Green

#1843 PURCHASE-1397 - Artwork view pull to refresh
  CHANGELOG.md
  data/complete.queryMap.json
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/ArtworkRefetchQuery.graphql.ts
  src/__generated__/Artwork_artwork.graphql.ts
  src/lib/Scenes/Artwork/Artwork.tsx
  src/lib/Scenes/Artwork/__tests__/Artwork-tests.tsx
Labels: Jira Synced

#1845 Report all data load errors when not in tests
  src/lib/utils/renderWithLoadProgress.tsx
Labels: Merge On Green

#1847 [package] Update vscode-apollo-relay to v1.1.1
  package.json
  yarn.lock
Labels: Merge On Green

#1849 PURCHASE-1464 [BidFlow] Fixes bug when clicking Next between fields in Billing Address form
  src/lib/Components/Bidding/Screens/BillingAddress.tsx
Labels: Merge On Green

#1852 [package] Update vscode-apollo-relay to v1.3.0
  package.json
  src/__generated__/CitySectionList_city.graphql.ts
  src/lib/Scenes/City/CitySectionList.tsx
  yarn.lock
Labels: Merge On Green

#1848 PURCHASE-1435 - Handles Ask a Specialist
  CHANGELOG.md
  Example/Emission/ARRootViewController.m
  data/complete.queryMap.json
  src/__generated__/ArtworkExtraLinks_artwork.graphql.ts
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/ArtworkRefetchQuery.graphql.ts
  src/lib/Scenes/Artwork/Components/ArtworkExtraLinks.tsx
Labels: Jira Synced, Merge On Green

#1855 [BNMO] Uses metaphysics string to display VAT information
  data/complete.queryMap.json
  data/schema.graphql
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/ArtworkRefetchQuery.graphql.ts
  src/__generated__/CommercialPartnerInformation_artwork.graphql.ts
  src/lib/Scenes/Artwork/Components/CommercialPartnerInformation.tsx
  src/lib/Scenes/Artwork/Components/__tests__/CommercialPartnerInformation-tests.tsx
Labels: Merge On Green

#1861 PURCHASE-1484 prevent crashes when staging image data is corrupt
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
Labels: Jira Synced, Merge On Green

#1862 [Artwork View] PURCHASE-1485 - Analytics fixes and updates
  src/lib/AppRegistry.tsx
  src/lib/Components/ArtistListItem.tsx
  src/lib/Components/Show/ShowArtistsPreview.tsx
  src/lib/Scenes/Artwork/Components/ArtworkActions.tsx
  src/lib/Scenes/Artwork/Components/ArtworkExtraLinks.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/MakeOfferButton.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarouselEmbedded.tsx
  src/lib/Scenes/Artwork/Components/OtherWorks/ContextGridCTA.tsx
  src/lib/Scenes/Artwork/Components/OtherWorks/OtherWorks.tsx
  src/lib/Scenes/Artwork/Components/PartnerCard.tsx
  src/lib/utils/track/schema.ts
Labels: Jira Synced

#1863 PURCHASE-1488 increase image carousel base resolution
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
Labels: Jira Synced, Merge On Green

#1865 Use screen pixel density rather than constant
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
Labels: Merge On Green

#1866 [Home] Stop scroll-to-top behaviour on Artists/Auctions tabs.
  CHANGELOG.md
  src/lib/Scenes/Home/index.tsx
Labels: Home, Jira Synced, Merge On Green

#1873 Fixes empty space in Artwork view
  src/lib/Scenes/Artwork/Components/CommercialInformation.tsx
Labels: Merge On Green

#1871 Fix analytics bug
  src/lib/Scenes/Artwork/Components/ArtworkTombstone.tsx
Labels: Merge On Green

#1875 Fixes bid badges aligment
  src/lib/Components/ArtworkGrids/ArtworkGridItem.tsx
  src/lib/Components/ArtworkGrids/__tests__/__snapshots__/ArtworkGridItem-tests.tsx.snap
Labels: Merge On Green

#1870 Fixes mock in ConversationSnippet
  src/lib/Components/Inbox/Conversations/__stories__/ConversationSnippet.story.tsx
  src/lib/Components/Inbox/Conversations/__tests__/ConversationSnippet-tests.tsx
  src/lib/Components/Inbox/Conversations/__tests__/__snapshots__/ConversationSnippet-tests.tsx.snap
Labels: Merge On Green

#1880 [Home] Stop scroll-to-top behaviour on Artists/Auctions tabs.
  CHANGELOG.md
  src/lib/Scenes/Home/index.tsx
Labels: Home, Jira Synced, Merge On Green

#1884 Fix wrong input param and switch to new fancy shiny cammelCase one #trivial
  src/lib/Components/Consignments/Submission/__tests__/consignmentSetupToSubmission-tests.ts
  src/lib/Components/Consignments/Submission/consignmentSetupToSubmission.ts
Labels: Jira Synced, Merge On Green

#1878 PURCHASE-1492, PURCHASE-1489: "Save" should be "Watch" on all lots, Remove "from artsy specialist" in description for auction artworks
  data/complete.queryMap.json
  src/__generated__/AboutWork_artwork.graphql.ts
  src/__generated__/ArtworkActionsTestsErrorQuery.graphql.ts
  src/__generated__/ArtworkActionsTestsQuery.graphql.ts
  src/__generated__/ArtworkActions_artwork.graphql.ts
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/ArtworkRefetchQuery.graphql.ts
  src/lib/Scenes/Artwork/Components/AboutWork.tsx
  src/lib/Scenes/Artwork/Components/ArtworkActions.tsx
  src/lib/Scenes/Artwork/Components/__stories__/AboutWork.story.tsx
  src/lib/Scenes/Artwork/Components/__stories__/ArtworkActions.story.tsx
  src/lib/Scenes/Artwork/Components/__tests__/AboutWork-tests.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ArtworkActions-tests.tsx
Labels: Jira Synced, Merge On Green

#1887 PURCHASE-1510 Disable submit button in consignments flow
  Example/Podfile.lock
  patches/react-native+0.59.2.patch
  src/lib/Components/Consignments/Components/FormElements.tsx
  src/lib/Components/Consignments/Screens/Overview.tsx
Labels: Jira Synced

#1890 PURCHASE-1513 Refetches Artwork page query on re-appear
  CHANGELOG.md
  src/lib/AppRegistry.tsx
  src/lib/Scenes/Artwork/Artwork.tsx
  src/lib/Scenes/Artwork/__stories__/Artwork.story.tsx
  src/lib/Scenes/Artwork/__tests__/Artwork-tests.tsx
Labels: Merge On Green

#1885 PURCHASE-1496: Auction actions and info still render when work has sold via buy now
  data/complete.queryMap.json
  src/__generated__/ArtworkExtraLinks_artwork.graphql.ts
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/ArtworkRefetchQuery.graphql.ts
  src/__generated__/CommercialButtonsTestsMutationQuery.graphql.ts
  src/__generated__/CommercialButtonsTestsRenderQuery.graphql.ts
  src/__generated__/CommercialButtons_artwork.graphql.ts
  src/__generated__/CommercialInformation_artwork.graphql.ts
  src/lib/Scenes/Artwork/Components/ArtworkExtraLinks.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/CommercialButtons.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/__tests__/CommercialButtons-tests.tsx
  src/lib/Scenes/Artwork/Components/CommercialInformation.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ArtworkExtraLinks-tests.tsx
  src/lib/Scenes/Artwork/Components/__tests__/CommercialInformation-tests.tsx
Labels: Jira Synced

#1891 Track more auction events
  CHANGELOG.md
  src/lib/Scenes/Artwork/Components/ArtworkExtraLinks.tsx
  src/lib/Scenes/Artwork/Components/CommercialButtons/BidButton.tsx
  src/lib/Scenes/Artwork/Components/__tests__/ArtworkExtraLinks-tests.tsx
  src/lib/tests/mockTracking.ts
  src/lib/utils/track/schema.ts
Labels: Jira Synced

#1893 [PURCHASE-1519] Fixes issue where the Artwork page would show a refresh animation on re-appear
  CHANGELOG.md
  src/lib/Scenes/Artwork/Artwork.tsx
Labels: Merge On Green
