Repository artsy/emission, pull requests merged in 2020-01, with the labels that each got.

#2021 Adds full bleed to collections header
  Pod/Classes/ViewControllers/ARCollectionComponentViewController.m
Labels: Version: Patch

#2025 [MX-140] CCPA infrastructure
  Example/Emission/ARRootViewController.m
  Example/Emission/AppDelegate.m
  Example/Podfile.lock
  Pod/Classes/ViewControllers/ARMyProfileComponentViewController.h
  Pod/Classes/ViewControllers/ARMyProfileComponentViewController.m
  Pod/Classes/ViewControllers/ARMyProfileEditViewController.m
  Pod/Classes/ViewControllers/ARPrivacyRequestComponentViewController.h
  Pod/Classes/ViewControllers/ARPrivacyRequestComponentViewController.m
  package.json
  src/__generated__/MyProfile_me.graphql.ts
  src/__generated__/QueryRenderersMyProfileQuery.graphql.ts
  src/lib/AppRegistry.tsx
  src/lib/Icons/Gear.tsx
  src/lib/Scenes/Favorites/index.tsx
  src/lib/Scenes/PrivacyRequest/PrivacyRequest.tsx
  src/lib/Scenes/PrivacyRequest/index.tsx
  src/lib/Scenes/Settings/MyProfile.tsx
  src/lib/Scenes/Settings/__stories__/Settings.story.tsx
  src/lib/Scenes/Settings/__tests__/MyProfile-tests.tsx
  src/lib/Scenes/Settings/__tests__/__snapshots__/MyProfile-tests.tsx.snap
  src/lib/relay/QueryRenderers.tsx
  src/lib/utils/router.ts
Labels: Merge On Green, Version: Minor

#2028 Excludes mocks from requiring their own unit tests
  dangerfile.ts
Labels: Merge On Green

#2027 Adds log out button to app
  Pod/Classes/Core/AREmission.h
  Pod/Classes/Core/AREmission.m
  Pod/Classes/ViewControllers/ARPrivacyRequestComponentViewController.h
  Pod/Classes/ViewControllers/ARPrivacyRequestComponentViewController.m
  data/complete.queryMap.json
  package.json
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/ArtworkRailRefetchQuery.graphql.ts
  src/__generated__/ArtworkRefetchQuery.graphql.ts
  src/__generated__/ArtworkTestsQuery.graphql.ts
  src/__generated__/ForYouRefetchQuery.graphql.ts
  src/__generated__/LoggedInUserInfoQuery.graphql.ts
  src/__generated__/LoggedInUserInfo_me.graphql.ts
  src/__generated__/QueryRenderersForYouQuery.graphql.ts
  src/lib/Scenes/Favorites/index.tsx
  src/lib/Scenes/Settings/LoggedInUserInfo.tsx
  src/lib/Scenes/Settings/MyProfile.tsx
  src/lib/Scenes/Settings/__mocks__/LoggedInUserInfo.tsx
  src/lib/Scenes/Settings/__tests__/LoggedInUserInfo-tests.tsx
  src/lib/Scenes/Settings/__tests__/MyProfile-tests.tsx
  src/lib/Scenes/Settings/__tests__/__snapshots__/MyProfile-tests.tsx.snap
Labels: Merge On Green, Version: Patch

#2029 Changes settings screen to use sentence case #trivial
  src/lib/Scenes/Settings/MyProfile.tsx
  src/lib/Scenes/Settings/__tests__/__snapshots__/MyProfile-tests.tsx.snap
Labels: Version: Patch

#2030 Adds missing cursor to collection artwork pagination query
  data/complete.queryMap.json
  src/__generated__/CollectionArtworksInfiniteScrollGridQuery.graphql.ts
  src/__generated__/CollectionArtworks_collection.graphql.ts
  src/lib/Scenes/Collection/Screens/CollectionArtworks.tsx
Labels: Version: Patch

#2032 Featured artists module rebase
  Example/Podfile.lock
  data/complete.queryMap.json
  src/__generated__/CollectionTestsQuery.graphql.ts
  src/__generated__/Collection_collection.graphql.ts
  src/__generated__/FeaturedArtistsTestsQuery.graphql.ts
  src/__generated__/FeaturedArtists_collection.graphql.ts
  src/__generated__/QueryRenderersCollectionQuery.graphql.ts
  src/lib/Scenes/Collection/Collection.tsx
  src/lib/Scenes/Collection/Components/FeaturedArtists.tsx
  src/lib/Scenes/Collection/Components/__tests__/FeaturedArtists-tests.tsx
  src/lib/Scenes/Collection/Components/__tests__/__snapshots__/FeaturedArtists-tests.tsx.snap
  src/lib/Scenes/Collection/__tests__/__snapshots__/Collection-tests.tsx.snap
Labels: Version: Patch

#2033 Pass screen width in a variable to relay resize artworks query
  data/complete.queryMap.json
  src/__generated__/CollectionTestsQuery.graphql.ts
  src/__generated__/Collection_collection.graphql.ts
  src/__generated__/FeaturedArtists_collection.graphql.ts
  src/__generated__/QueryRenderersCollectionQuery.graphql.ts
  src/lib/Scenes/Collection/Collection.tsx
  src/lib/Scenes/Collection/Components/FeaturedArtists.tsx
  src/lib/Scenes/Collection/__tests__/__snapshots__/Collection-tests.tsx.snap
  src/lib/relay/QueryRenderers.tsx
Labels: Version: Patch

#2026 Updates to Xcode 11
  .circleci/config.yml
  .nvmrc
  CHANGELOG.md
  Example/Emission.xcodeproj/project.pbxproj
  Example/Emission.xcodeproj/xcshareddata/xcschemes/Emission Example.xcscheme
  Example/Emission.xcodeproj/xcshareddata/xcschemes/Emission.xcscheme
  Example/Podfile
  Example/Podfile.lock
  Pod/Assets/assets/data/complete.queryMap.json
Labels: Merge On Green

#2034 Installs Node 12 on deploy build #trivial
  .circleci/config.yml
Labels: Merge On Green, Version: Patch

#2031 [MX-135] - Null checks for optional show.kind metadata
  src/lib/Components/Artist/ArtistShows/Metadata.tsx
  src/lib/Components/Artist/ArtistShows/__tests__/ArtistShow-tests.tsx
  src/lib/Components/Artist/ArtistShows/__tests__/__snapshots__/ArtistShow-tests.tsx.snap
Labels: Version: Patch

#2037 Exclude specified artists from featured artist list [FX-1717]
  data/complete.queryMap.json
  src/__generated__/CollectionTestsQuery.graphql.ts
  src/__generated__/FeaturedArtistsTestsQuery.graphql.ts
  src/__generated__/FeaturedArtists_collection.graphql.ts
  src/__generated__/QueryRenderersCollectionQuery.graphql.ts
  src/lib/Scenes/Collection/Components/FeaturedArtists.tsx
  src/lib/Scenes/Collection/Components/__tests__/FeaturedArtists-tests.tsx
  src/lib/Scenes/Collection/__tests__/__snapshots__/Collection-tests.tsx.snap
Labels: Version: Patch

#2038 [MX-141] [MX-144] Adds feedback/privacy request user interface
  Emission.podspec
  Pod/Classes/Core/ARSwitchBoardModule.m
  package.json
  src/lib/Icons/Gear.tsx
  src/lib/NativeModules/SwitchBoard.tsx
  src/lib/Scenes/Favorites/index.tsx
  src/lib/Scenes/PrivacyRequest/PrivacyRequest.tsx
  src/lib/Scenes/PrivacyRequest/__tests__/PrivacyRequest-tests.tsx
  src/lib/Scenes/Settings/MyProfile.tsx
  src/lib/Scenes/Settings/__tests__/__snapshots__/MyProfile-tests.tsx.snap
Labels: Version: Patch

#2035 Collections metadata
  data/complete.queryMap.json
  data/schema.graphql
  src/__generated__/CollectionArtworksInfiniteScrollGridQuery.graphql.ts
  src/__generated__/CollectionArtworks_collection.graphql.ts
  src/__generated__/CollectionHeaderTestsQuery.graphql.ts
  src/__generated__/CollectionHeader_collection.graphql.ts
  src/__generated__/CollectionTestsQuery.graphql.ts
  src/__generated__/Collection_collection.graphql.ts
  src/__generated__/QueryRenderersCollectionQuery.graphql.ts
  src/lib/Scenes/Collection/Collection.tsx
  src/lib/Scenes/Collection/Components/__fixtures__/CollectionFixture.ts
  src/lib/Scenes/Collection/Screens/CollectionArtworks.tsx
  src/lib/Scenes/Collection/Screens/CollectionHeader.tsx
  src/lib/Scenes/Collection/Screens/__tests__/CollectionHeader-tests.tsx
  src/lib/Scenes/Collection/__tests__/__snapshots__/Collection-tests.tsx.snap
  src/lib/utils/track/schema.ts
Labels: Merge On Green, Version: Patch

#2039 [FX-1716] Constrain collection's featured artists
  data/complete.queryMap.json
  src/__generated__/CollectionTestsQuery.graphql.ts
  src/__generated__/FeaturedArtistsTestsQuery.graphql.ts
  src/__generated__/FeaturedArtists_collection.graphql.ts
  src/__generated__/QueryRenderersCollectionQuery.graphql.ts
  src/lib/Scenes/Collection/Components/FeaturedArtists.tsx
  src/lib/Scenes/Collection/Components/__tests__/FeaturedArtists-tests.tsx
  src/lib/Scenes/Collection/__stories__/Collection.story.tsx
  src/lib/Scenes/Collection/__tests__/__snapshots__/Collection-tests.tsx.snap
  storybook/storyLoader.js
Labels: Version: Patch

#2041 Changes header to Sans font #trivial
  src/lib/Scenes/PrivacyRequest/PrivacyRequest.tsx
  src/lib/Scenes/Settings/MyProfile.tsx
  src/lib/Scenes/Settings/__tests__/__snapshots__/MyProfile-tests.tsx.snap
Labels: Version: Patch

#2043 [MX-150] New search page analytics
  data/complete.queryMap.json
  src/__generated__/AutosuggestResultsPaginationQuery.graphql.ts
  src/__generated__/AutosuggestResultsQuery.graphql.ts
  src/__generated__/AutosuggestResults_results.graphql.ts
  src/lib/Components/__tests__/ReadMore-tests.tsx
  src/lib/Scenes/Search/AutosuggestResults.tsx
  src/lib/Scenes/Search/Input.tsx
  src/lib/Scenes/Search/Search.tsx
  src/lib/Scenes/Search/SearchContext.tsx
  src/lib/Scenes/Search/SearchResult.tsx
  src/lib/Scenes/Search/__tests__/AutosuggestResults-tests.tsx
  src/lib/Scenes/Search/__tests__/SearchResult-tests.tsx
  src/lib/utils/__tests__/track-tests.ts
  src/lib/utils/track/schema.ts
  src/setupJest.ts
Labels: Merge On Green, Version: Patch

#2045 Fixes bug causing image to fail to render in collection header
  src/lib/Scenes/Collection/Screens/CollectionHeader.tsx
  src/lib/Scenes/Collection/__tests__/__snapshots__/Collection-tests.tsx.snap
Labels: Version: Patch

#2046 Removes CocoaPods Specs repo setup
  .circleci/config.yml
Labels: Version: Patch

#2040 [MX-137] Use XCirlceIcon
  src/lib/Scenes/Search/Input.tsx
Labels: Version: Patch

#2048 Updates point people
  README.md
Labels: Merge On Green

#2053 [MX-153] Truncate search result titles at one line
  src/lib/Scenes/Search/SearchResult.tsx
Labels: Version: Patch

#2056 [MX-155] set consignments vc background color
  Pod/Classes/ViewControllers/ARShowConsignmentsFlowViewController.m
  package.json
Labels: Version: Patch

#2058 [MX-96] Remove redundant screen view tracking for Artist page
  src/lib/Containers/Artist.tsx
Labels: Merge On Green, Version: Patch

#2055 Collections Metadata QA Fixes
  src/lib/Scenes/Collection/Screens/CollectionHeader.tsx
Labels: Version: Patch

#2057 [FX-1750] Use explicit size param for collection header's featured artists
  data/complete.queryMap.json
  data/schema.graphql
  src/__generated__/CollectionTestsQuery.graphql.ts
  src/__generated__/FeaturedArtistsTestsQuery.graphql.ts
  src/__generated__/FeaturedArtists_collection.graphql.ts
  src/__generated__/QueryRenderersCollectionQuery.graphql.ts
  src/lib/Scenes/Collection/Components/FeaturedArtists.tsx
  src/lib/Scenes/Collection/__tests__/__snapshots__/Collection-tests.tsx.snap
Labels: Version: Patch

#2062 Fixes issue with Artist tracking components #trivial
  src/lib/Containers/Artist.tsx
Labels: Merge On Green, Version: Patch

#2052 [FX-1729] tracking for collections
  src/lib/Scenes/Collection/Components/FeaturedArtists.tsx
  src/lib/Scenes/Collection/Components/__tests__/FeaturedArtists-tests.tsx
  src/lib/Scenes/Collection/Components/__tests__/__snapshots__/FeaturedArtists-tests.tsx.snap
  src/lib/Scenes/Collection/Screens/CollectionHeader.tsx
  src/lib/utils/track/schema.ts
Labels: Merge On Green, Version: Patch

#2060 Fixes resizing bug on collection header images
  data/complete.queryMap.json
  src/__generated__/CollectionHeaderTestsQuery.graphql.ts
  src/__generated__/CollectionHeader_collection.graphql.ts
  src/__generated__/CollectionTestsQuery.graphql.ts
  src/__generated__/Collection_collection.graphql.ts
  src/__generated__/QueryRenderersCollectionQuery.graphql.ts
  src/lib/Scenes/Collection/Collection.tsx
  src/lib/Scenes/Collection/Components/__fixtures__/CollectionFixture.ts
  src/lib/Scenes/Collection/Screens/CollectionHeader.tsx
  src/lib/Scenes/Collection/__tests__/__snapshots__/Collection-tests.tsx.snap
Labels: Version: Patch

#2061 Fixes Consignments status bar content colour
  Pod/Classes/ViewControllers/ARShowConsignmentsFlowViewController.m
Labels: Version: Patch

#2064 Add missing event type for Collections' view-more-artists interaction
  src/lib/Scenes/Collection/Components/FeaturedArtists.tsx
  src/lib/Scenes/Collection/Components/__tests__/FeaturedArtists-tests.tsx
Labels: Version: Patch

#2063 reduce volley client error message noise in sentry
  src/lib/utils/volleyClient.ts
Labels: Version: Patch

#2059 [FX-1747] Refactor FeatureArtist component to use ArtistListItem component
  CHANGELOG.md
  Pod/Assets/assets/data/complete.queryMap.json
  data/complete.queryMap.json
  src/__generated__/CollectionTestsQuery.graphql.ts
  src/__generated__/Collection_collection.graphql.ts
  src/__generated__/FeaturedArtistsTestsQuery.graphql.ts
  src/__generated__/FeaturedArtists_collection.graphql.ts
  src/__generated__/QueryRenderersCollectionQuery.graphql.ts
  src/lib/Scenes/Collection/Collection.tsx
  src/lib/Scenes/Collection/Components/FeaturedArtists.tsx
  src/lib/Scenes/Collection/Components/__tests__/FeaturedArtists-tests.tsx
  src/lib/Scenes/Collection/Components/__tests__/__snapshots__/FeaturedArtists-tests.tsx.snap
  src/lib/Scenes/Collection/__tests__/__snapshots__/Collection-tests.tsx.snap
Labels: Version: Patch

#2065 Adds conditional padding to collection title
  src/lib/Scenes/Collection/Screens/CollectionHeader.tsx
  src/lib/Scenes/Collection/__tests__/__snapshots__/Collection-tests.tsx.snap
Labels: Version: Patch

#2066 [MX-166] handle images without deep zoom
  data/complete.queryMap.json
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/ArtworkRefetchQuery.graphql.ts
  src/__generated__/ArtworkTestsQuery.graphql.ts
  src/__generated__/ImageCarouselTestsQuery.graphql.ts
  src/__generated__/ImageCarousel_images.graphql.ts
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarousel.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarouselContext.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/ImageCarouselEmbedded.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/__tests__/ImageCarousel-tests.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/__tests__/ImageCarouselContext-tests.tsx
  src/lib/Scenes/Artwork/Components/ImageCarousel/__tests__/ImageCarouselEmbedded-tests.tsx
Labels: Merge On Green, Version: Patch

#2069 Update analytics constant for Collection/Featured Artists
  src/lib/Scenes/Collection/Components/FeaturedArtists.tsx
Labels: Version: Patch
